# Đạo Phật với tuổi trẻ {- #dao-phat-voi-tuoi-tre}

Lâu nay đa số người Việt Nam cho rằng: Ðạo Phật là dành riêng cho các bậc già nua tuổi tác, nhờ câu kinh tiếng kệ an ủi những ngày tàn. Hoặc kẻ bị tình đời đen bạc hay người đã mấy phen vấp ngã trên bước công danh quay về nương tựa cửa thiền, nhờ giọt nước cành dương rưới dịu đôi phần sầu hận. Hoặc những người đau ốm tật nguyền sống thừa thãi ngoài xã hội về núp bóng từ bi, nhờ hột cơm, manh áo của đàn-na tín thí để đỡ phần cơ cực... Quan niệm ấy đã ăn sâu trong tâm não dân chúng, nên khi thấy một thanh niên cạo tóc xuất gia, hoặc đến chùa lễ Phật thì họ xầm xì cho là chán đời, là bi quan, là trốn nợ xã hội. Nhưng họ đâu ngờ đạo Phật là **"đạo của tuổi thanh xuân đang căng nhựa sống và tha thiết yêu đời"**.  
  
Nói thế, không phải cố gò bó đạo Phật cho gần với tuổi trẻ, mà vì thật tánh của đạo Phật rất thích hợp với hàng hoa niên. Sự thích hợp ấy bởi những điểm như sau:  
  
## Thanh tịnh {- #thanh-tinh}

Ðạo Phật cốt đào luyện tâm hồn người hoàn toàn trong sạch, nên cực lực sa thải những tính: tham lam, sân hận, oán thù... đang trú ẩn trong tâm giới người. Nhưng từ lúc thanh niên, người ta phải cất mình ra khỏi cổng nhà cha mẹ, bắt tay vào việc cạnh tranh, chiến đấu với đời, từ đó những tánh xấu, tham lam, sân hận... càng ngày tập nhiễm càng sâu, đến đen tối cả tâm hồn. Lúc tuổi già muốn gột rửa nó là cả một sự khó khăn. Như chiếc áo trắng đã nhuộm chàm, muốn giặt tẩy trắng lại không phải là việc dễ. Trái lại, tuổi thiếu niên tâm hồn còn trong trắng, những tính xấu nếu có, cũng chỉ một vài điểm nhỏ thôi. Nếu họ sớm biết thức tỉnh quyết tâm tẩy trừ thì rất dễ dàng, như chiếc áo trắng vừa vấy vài vết nhơ, giặt tẩy rất mau sạch. Vì thế tuổi thiếu niên rất thích hợp với đức thanh tịnh của đạo Phật.  
  
## Chân thật {- #chan-that}

Ðạo Phật là đạo như thật, người tu theo đạo Phật cần phải xa lìa những điều giả dối để trở về với sự thật. Phật cấm nói dối và dạy quán vô thường, bất tịnh, khổ... đều nhắm mục đích này. Tuổi trẻ là ngây thơ chất phác, nghĩ sao nói vậy, nên ít biết dối trá xảo quyệt. Nhưng đến lúc thành niên, để bắt chước theo thói xã giao, hoặc vì sự mưu sanh, người ta lần lần tập nhiễm những điều xảo trá và xa dần sự thật. Khi đi xa mà muốn quay về là nhọc nhằn hơn lúc ở gần. Vì thế tuổi trẻ còn chất phác, nhiều thành thật, nên rất gần với đạo Phật.  
  
## Từ bi {- #tu-bi}

Ðạo Phật là đạo Từ bi, là đạo cứu khổ chúng sanh bằng mọi phương tiện và mọi hình thức. Người tu theo đạo Phật là hy sinh đời mình để mưu hạnh phúc cho chúng sanh, và mở tâm lượng bao la trùm tất cả mọi loài trong tình thương bình đẳng. Với tâm lượng ấy, với chí hy sinh ấy, người lưng còng, má cóp có thể đảm đang nổi chăng? Người ốm đau bệnh tật có thể gánh vác được không? Và người thực hiện được điều này có thể gọi là bi quan yếm thế chăng? - Cố nhiên phải là người niên tráng lực cường, thân hình căng đầy nhựa sống, mới đủ khả năng sớt cơm, chia áo và gánh vác những điều khó khổ nhọc nhằn cho chúng sanh.  

Hơn nữa, tuổi thiếu niên là tuổi phóng tầm mắt nhìn khắp vũ trụ bao la và muốn ôm cả nhân loại vào lòng; nhưng đến khi đã cột mình trong bổn phận làm vợ, làm chồng, làm cha, làm mẹ... thì chí cả ấy bị đóng khung trong gian nhà chật hẹp của gia đình, rồi dần dần nó bị tiêu ma như hạt sương tan theo dưới ánh nắng. Ðang khi tâm hồn khoáng đãng của tuổi thanh xuân mà gặp được tình thương vô bờ bến của tâm lượng Từ bi thì: Ôi! Sung sướng nào hơn nữa?!  
  
## Tinh tấn {- #tinh-tan}

Phật quả là một quả vị vô thượng. Người muốn đạt được quả vị này phải trải lắm công phu nhọc nhằn khổ sở, với thời gian dài đằng đẵng, đâu phải tu một sớm một chiều mà chứng được, trừ những bậc Bồ-tát thị hiện. Công trình tu tập như một bộ hành trèo núi cao mấy mươi cây số; muốn đến được đỉnh, người bộ hành phải dẫm qua lắm đoạn đường chông gai, đá sỏi, vượt qua nhiều vách đá cheo leo và trải qua những đèo cao, hố thẳm, nhiên hậu mới mong ngồi bóng mát trên đầu non chót vót và ngắm xem bức sơn thủy muôn màu ngàn sắc của trần gian. Như vậy, muốn thực hiện được công phu này, phải đòi hỏi ở người có cặp chân cứng rắn, đôi mắt tinh anh, sức lực dồi dào và đủ tinh thần quả cảm. Thanh niên là tuổi máu nóng đang lên, nhựa sống căng thẳng, đời sống còn dài, nên dễ thực hiện được công tác này. Ðức Thích-ca ngày xưa nếu đợi sáu, bảy mươi tuổi mới đi tu, chắc ngày nay chúng ta không biết được mùi pháp vị là gì.  
  
## Trí tuệ {- #tri-tue}

Ðức Phật là đấng đã giác ngộ. Người tu theo đạo Phật là noi theo con đường sáng suốt của Ngài đã qua để đến thành trì giác ngộ. Muốn được giác ngộ cần phải có trí tuệ, vì trí tuệ là ánh sáng quét sạch màn đêm và soi tỏ mọi vật, khiến chúng hiện bày chân tướng dưới mắt người. Tuy nhiên, muốn có trí tuệ ta cần phải có thân hình tráng kiện, như thường nói như: *"Một tâm hồn sáng suốt trong một thân thể tráng kiện"*; hay ngược lại, cũng thế. Như vậy tuổi trẻ rất dễ phát khởi trí tuệ, người già yếu trí tuệ cũng bị ảnh hưởng phải lu mờ. Bằng chứng, cùng một bài học mà người trẻ học mau thuộc, người già học rất lâu. Vì thế cho nên tuổi trẻ là tuổi rất thích hợp với đạo Phật.  
  
Mặc dù đạo Phật rất thích hợp với tuổi trẻ, nhưng với bậc lão thành, với người khổ sở, với kẻ chán đời... vẫn được đạo Phật tiếp độ. Vì đạo Phật là đạo bình đẳng, giáo lý Phật là giáo lý phổ biến vậy. Mái tóc xanh gần đạo Phật ở đức thanh tịnh... thì người đầu bạc cũng nhờ "tín" của đạo Phật mà vui vẻ những ngày tàn. Tuổi hoa niên thể theo đức từ bi mở rộng lòng thương, thì người khổ sở cũng nhờ bàn tay từ bi ấy xoa dịu đôi phần đau khổ. Hàng tráng niên đến với đạo Phật là cầu giác ngộ, cầu thành Phật quả; người chán đời đến với đạo Phật để nhờ câu kinh thâm diệu, nhịp mõ trầm hùng, tiếng chuông cảnh tỉnh mà lần lần cởi sạch mọi nỗi oán hờn.  
  
Tóm lại, đạo Phật là đạo chung tất cả, nhưng thích hợp nhất là tuổi trẻ. Vì tuổi trẻ mới có đủ phương tiện thực hiện triệt để giáo lý cao siêu của Phật, và tuổi trẻ mới đủ bầu nhiệt huyết hăng hái quả cảm trên con đường tự giác, giác tha, dù gặp mọi gian nguy khó khổ. Do đó nên Phật dạy bốn pháp kiên cố đến quả Bồ-đề, *"tuổi trẻ biết mộ đạo tu hành"* là một trong bốn điều ấy vậy.  

Tuổi trẻ là tuổi thích hợp với đạo Phật, vậy những bạn thanh niên không nên luống phí thời giờ, phí thời kỳ quí báu ấy, đợi đến khi sức kiệt hơi tàn, có hối tiếc cũng không kịp. Phật dạy:  

> Ngươi nói: *"Tôi còn trẻ cần phải chơi bời vui vẻ, đến ngày già sẽ tu"*. Nhưng cái chết có khác nào kẻ cướp cầm gươm bén theo rình rập ngươi, một miếng mồi ngon của nó. Như vậy làm sao ngươi chắc mà đợi đến ngày già đặng đưa tâm trí qua đường Ðạo đức?  
