# Đức hỉ xả {- #duc-hi-xa}

Sống trên đấu trường nhân loại, trong cõi đời trần tục nhiễm ô, nếu ai cố ôm chặt lòng thù hận chấp nê thì không sao tránh khỏi cảnh lầm than đau khổ. Muốn thoát khổ được vui, con người phải gỡ bỏ những mối dây oán hận, tẩy sạch những vết nhơ ô nhiễm trong cõi lòng mình cho được nhẹ nhàng trong sạch. Phương pháp gỡ bỏ và tẩy trừ ấy là đức hỉ xả.  
  
Hỉ xả là vui vẻ tha thứ những lỗi lầm mà người đã phạm đến ta, cũng như vui vẻ bỏ tất cả danh vọng, tài sắc cho đến thân mạng của ta, nếu thấy cần và lợi ích cho chúng sanh. Có tha thứ, lòng ta mới thênh thang, tim ta mới hòa nhịp cùng tim của mọi người, có xả bỏ, tâm ta mới thanh thoát và an tịnh.  
  
Cuộc đời đen tối và sầu khổ nhất là cuộc đời của kẻ hay cau có, oán thù. Vì kẻ hay cau có thì trên gương mặt luôn luôn hiện đầy những nét nhăn gay gắt, đôi mi chau lại lộ vẻ khó khăn. Kẻ còn ôm nặng khối hận thù thì lửa hận thù thiêu đốt cả tim gan và buồng phổi của họ. Còn gì khổ đau hơn khi tim gan bị thiêu đốt. Còn gì xấu xí bằng khi gương mặt nhăn nhó, héo sầu.  

Sống trên đời này, nếu ta gặp điều trái ý liền mang lòng thù hận, thì chắc đời ta sẽ thấy toàn thù hận và oán hờn. Như Tý dùng lời thô bỉ mắng Thân, Thân cố trả thù phải dùng lời bỉ ổi hơn. Ban đầu còn trả thù nhau bằng miệng, kế trả thù bằng tay chân và sau cùng phải trả thù nhau bằng dao, búa. Khi sơ khởi chỉ là mối thù riêng của cá nhân, rồi lan dần đến mối thù chung của gia đình, của thân tộc. Cứ thế, oán thù chập chồng thêm mãi biết bao giờ dứt. Ðức Phật dạy:  

> Lấy oán trả oán, oán mãi chất chồng. Lấy ân trả oán, oán liền tiêu diệt.  

Người trong lòng mãi ôm ấp hận thù thì lúc nào cũng tưởng chừng chung quanh đều là kẻ thù muốn hại mình, vì vậy họ sống những ngày đầy lo sợ. Chỉ có ai biết lấy ân trả oán mới mong dứt sạch được hận thù. Như người Ðình Trưởng nước Lương trả thù người cào dưa mình bằng cách ra công tưới dưa cho người, nhờ đó mà hận thù dứt sạch.  
  
Còn gì vui sướng hơn, kẻ có tâm lượng bao dung sẵn sàng tha thứ mọi lỗi lầm cho người. Khi nào trong lòng ta không còn một mảy may thắc mắc, không còn một chút bợn hận thù, đó là lúc ta hoàn toàn an lạc. Người mà lòng được thanh thoát nhẹ nhàng thì gương mặt vui tươi, lời nói thanh nhã, cử chỉ thư thái, toàn thân hiện ra một phong độ khả ái khả kính. Con người ấy có mấy khi phải buồn khổ, vì thế nên họ trẻ mãi, sống dai. Sách có câu:  

> Thù ghét là sâu mọt đục khoét người ta, làm cho người ta chóng xấu, chóng già, chóng chết. Yêu thương và tha thứ là suối nước cam lồ tưới vào lòng người, làm cho người tươi đẹp, trẻ dai và sống mãi.  
  
Danh vọng, tài sắc... ở đời là những cạm bẫy chực hại người, nhưng vì nó có công năng hấp dẫn quyến rũ khiến người phải mê mẩn say sưa để rồi chịu khổ, cũng như miếng mồi vì có mùi thơm hấp dẫn, con lươn phải lao đầu vào hom trúm. Phần đông người đời ngỡ rằng đuổi bắt tài sắc, danh vọng... là hạnh phúc, chớ đâu ngờ càng đuổi bắt nó càng chuốc khổ về mình. Ðây, một chàng thanh niên ủ dột ngồi dưới lùm cổ thọ, phải chăng chàng đã trật chân trên nấc thang danh vọng? Kia, một thiếu nữ sầu bi đứng dựa mé sông sâu, phải chăng vì tình duyên ngang trái? Tóm lại, bởi đắm nhiễm sắc, tài, danh vọng... người đời phải luống chịu đau khổ.  
  
Dứt bỏ những tham nhiễm là điều không phải dễ, mà dứt bỏ một cách vui vẻ lại càng khó hơn. Nếu ai mắt thấy sắc đẹp, tai nghe tiếng hay... mà lòng không ái nhiễm, ấy là bực siêu nhân. Ngài Phù Dung Thiền sư nói:  

> "... ngộ thanh ngộ sắc như thạch thượng tài hoa, kiến lợi kiến danh như nhãn trung trước tiết..."  

Nghĩa là:  

> "... nghe tiếng hay, nhìn sắc đẹp như hoa trồng trên đá, thấy tài lợi danh vọng như bụi rơi vào mắt..."  

Con người được như vậy mới hẳn là tự tại an vui. Chúng ta nhìn qua tượng đức Di-lặc sẽ thấy năm đứa nhỏ móc tai, chọc mắt... Ngài, mà trên gương mặt Ngài vẫn nở một nụ cười tự tại. Hình dáng ấy để tượng trưng cho người đã hỉ xả ngũ trần toàn vẹn. Ðức Di-lặc không cười sao đặng, vì ngoại cảnh còn gì quyến rũ được Ngài, tâm Ngài lúc nào cũng an nhiên thì quyết định trên gương mặt hẳn luôn luôn hoan hỉ.  
  
Tài, sắc, danh vọng... là vật bên ngoài, xả bỏ không lấy gì làm khó, đến như thân mạng là cái mà người phàm phu tuyệt đối mến yêu, muốn xả bỏ nó thì sự khó khăn lại gấp bội phần. Người đời vì trìu mến thân nên đã gây biết bao tội lỗi, ngược lại:  

> "Bồ-tát vì chúng sanh bỏ thân mạng dễ dàng hơn người tham lẫn bỏ một vắt cơm."  
> <div class="align-right">-- Luận Ðại Trượng Phu</div>
  
Người đã quên mình vì chúng sanh thì đối với sự khổ vui còn mất của thân mình không đáng kể, như thế là họ đã vượt khỏi cái khổ vì thân. Lão Tử nói:  

> Ngô hữu đại hoạn vị ngô hữu thân, ngô nhược vô thân hà hoạn chi hữu.

Thật vậy, nếu không còn thấy có riêng mình thì còn hoạn gì làm cho mình khổ. Vui lòng bỏ thân mạng để cứu độ chúng sanh, đó là đức hỉ xả cứu kính.  
  
Tóm lại, hỉ xả những oán thù cho lòng được nhẹ lòng thanh thoát, đó là cái vui của phàm nhân. Hỉ xả những tài, sắc, danh vọng... cho tâm được tự tại, đó là cái vui của bậc giải thoát. Hỉ xả thân mạng để cứu độ chúng sanh, làm cho tất cả chúng sanh được an lạc, đó là cái vui của bậc Bồ-tát. Người Phật tử quyết tâm dứt khổ tìm vui, phải tu đức hỉ xả theo thứ tự của nó, hỉ xả một phần là chúng ta được vui một bậc. Ðến khi nào hỉ xả toàn vẹn rồi là ta được cái vui cứu kính. Như vậy, vui và khổ không phải do ai đem đến hay ban cho, mà chính ta tự tạo lấy.  

