# Đức thanh tịnh {- #duc-thanh-tinh}

Muốn xây dựng một xã hội tốt đẹp mà không lo hoán cải con người, ấy chỉ là việc mò trăng đáy giếng. Nhằm mục đích xây dựng xã hội, đạo Phật bắt đầu hoán cải từng cá nhân, chẳng những trong hạng thành niên, mà đến hàng trẻ thơ non dại. Nền tảng tạo thành một con người tốt đẹp là thanh tịnh.  

Thanh tịnh là trong sạch. Trong sạch không có nghĩa thoát ly ngoài cảnh trần tục, mà chỉ ở ngay trong cõi đời ô trược, nhưng không bị nhiễm ô, thế mới thật là trong sạch. Như hoa sen tuy nằm giữa đống bùn nhớp nhúa, mà hương vị vẫn thơm tho. Vì thế khi nói đến đức thanh tịnh, đạo Phật hằng mượn hoa sen để biểu thị. Ðức Phật nghiễm nhiên ngự trên đài sen. Muốn thực hiện đức thanh tịnh, người Phật tử tập dần từ thô đến tế, từ cạn đến sâu theo thứ tự: hành động thanh tịnh, ngôn ngữ thanh tịnh, và tư tưởng thanh tịnh.  
  
## Hành động thanh tịnh {- #hanh-dong-thanh-tinh}

Trước nhất người Phật tử giữ gìn thân thể sạch sẽ, sự ăn mặc vén khéo giản dị, cho đến khi đi đứng phải đoan chính; tránh mọi xa hoa, phù phiếm và vô độ. Mặc một bộ đồ bóng dợn, ướp nước hoa nồng nặc... cử chỉ ấy, đối với người Phật tử vẫn thấy không thanh tịnh chút nào.  
  
Người Phật tử lập đức thanh tịnh, không bao giờ ỷ tài năng thế lực đánh đập, lấn hiếp người hay vật khi thấy họ thân cô, thế quả. Càng tránh xa hơn, đối với sự giết hại dù con vật nhỏ bé vô cớ, người Phật tử không nỡ giết. Vì đó là hành động xấu xa. Cho đến một cái nhìn ngạo nghễ, một cử chỉ khinh khi, người Phật tử cũng không khi nào có. Bởi vì một hành động xấu xa dù lớn, dù bé cũng có thể làm hoen ố đời trắng trong của người Phật tử. Họ tránh xa những cử chỉ xấu như người hiền tránh xa những đám ẩu đả và đôi chối.  
  
Những hành động bạo ác, người Phật tử không bao giờ làm, nhưng với cử chỉ lành, hành động tốt, họ tích cực hoạt động. Vì hành động thanh tịnh không phải chỉ bảo thủ riêng mình mà phải cứu giúp nâng đỡ mọi người. Bởi thế nên bàn tay Phật tử lúc nào cũng chực vuốt thẳng những nét nhăn trên trán cho kẻ thảm sầu, thoa dịu những vết thương cho người đau khổ và lau khô giòng lệ lăn trên má của cô nhi... Bàn tay ấy sẽ mở lồng cho đàn chim sắp bị nhổ lông được vỗ cánh tung bay về bầu trời cao rộng, vỗ về một con vật bị người hành phạt đau thương, cho đến lượm gai trên đường rộng và nhặt đá trên lộ quan... Tựu trung, mọi hành động trên đều nhằm mục đích cứu người, cứu vật.  
  
## Ngôn ngữ thanh tịnh {- #ngon-ngu-thanh-tinh}

Lời nói là một lợi khí rất sắc bén, nó có thể giết người, giết mình một cách dễ dàng, nếu là lời nói ác. Nên Phật dạy:  

> Người đời lưỡi búa bén nằm sẵn trong miệng, sở dĩ giết mình do lời nói ác.  
  
Lời nói ác không chỉ mắng chửi, trù rủa... mà là nói lời ngọt như đường, êm như nhạc, nhưng để lừa bịp người, cũng là nói ác. Lời nói ác tức là bất tịnh, ô uế, nên người Phật tử không bao giờ để nó thốt ra nơi cửa miệng mình. Nếu lỡ vô tình hay bại trận vì cơn nóng giận đã thốt ra những lời thô ác, người Phật tử lấy làm nhục nhã, xấu hổ, phải chí thành sám hối và tuyệt đối không dám tái phạm.  
  
Lời nói có thể là lưỡi kiếm bén giết người nếu trong tay kẻ bạo ác, thì nó cũng có thể là cây đuốc sáng đưa người ra khỏi rừng mê, hay hoàn linh đơn cứu người trong cơn bệnh ngặt nếu trong tay nhà đạo đức, kẻ từ tâm. Vì thế người Phật tử cấm chỉ nói lời thô ác, nhưng thao thao nói những lời hiền hòa, êm dịu và chân thật. Rất cần những lời nói hiền hòa để khỏa bằng hầm hố thù hiềm đã đào sâu giữa mình và người, hoặc người với người. Có những lời êm dịu, ta mới khuyên lơn được những người uất hận khi gặp cảnh nghịch lòng, kẻ thất chí vì tình đời phụ bạc và tát vơi được phần nào nguồn lệ thảm của người tật nguyền, khốn khổ... Nhờ lời nói chân thật mới xiển dương được chân lý và vạch rõ lẽ chánh tà. Tóm lại, tất cả lời nói có tánh cách giúp ích người, có lợi cho xã hội đều là lời thanh tịnh, người Phật tử phải hằng tập và nói những lời ấy.  
  
## Tư tưởng thanh tịnh {- #tu-tuong-thanh-tinh}

Ðộng cơ chính gây nên tội ác, hoặc khiến đời sống con người phải ngầu đục, nhớp nhơ trong biển sanh tử là tư tưởng. Ngược lại, tạo vô lượng phước đức, đưa con người đến quả thanh tịnh giải thoát cũng do tư tưởng. Tư tưởng thủ một vai trọng yếu nhất trong đời người. Người nên, hư, tốt, xấu, tiến, thối... đều do tư tưởng quyết định. Vì thế người Phật tử phải gạn lọc đào thải những tư tưởng xấu, tăng trưởng những tư tưởng tốt, để tâm hồn được thanh tịnh.  
  
Muốn đào thải những tư tưởng xấu, ta phải anh dũng chiến thắng bọn giặc tham lam, sân hận, tự ái, ngã mạn..., xua đuổi chúng ra ngoài tâm giới ta. Bọn chúng được kêu một danh từ gọn hơn là "phiền não". Ngày nào bọn phiền não còn lẫn trong tâm ta, thì ngày ấy trí ta rối loạn, tâm ta vẩn đục. Phiền não là sóng, là cấu bợn, mà tâm là nước. Sóng dừng, cấu bợn lặng, tức là tâm nước trong.  

Sự ngầu đục trong tâm hồn ta bởi phiền não tạo nên, ta có thể dùng một vài bằng chứng để minh xác nó. Một tên bợm móc túi, sở dĩ dám thò tay móc túi người trước "thập mục sở thị" là vì nó chỉ thấy có tiền... hay nói bằng cách khác, nó trở thành tôi mọi của lòng gian tham sai sử. Nên chi lúc ấy, nó có thấy gì tù tội, biết gì xấu xa.  

Một bằng chứng nữa, khi ta gặp cảnh nghịch ý, cơn giận dữ nổi lên, khi đó ta còn đủ lý trí suy xét phải quấy nữa chăng, hay mặc tình để cho con quỉ giận dữ thúc đẩy? Nếu còn suy nghĩ kịp thì cơn giận tan, bởi đã nô lệ bọn quỉ sân hận, nên mới xảy ra cuộc xô xát bằng miệng, bằng tay. Người Phật tử muốn gạn lọc tư tưởng thanh tịnh quyết phải quả cảm, tích cực thanh trừng bọn giặc phiền não còn trú ẩn trong tâm mình.  
  
Chẳng những thế, Phật tử cần tăng trưởng tư tưởng từ bi hỉ xả. Tâm ta chẳng khác một mảnh đất mầu mỡ, nếu không có lúa khoai thì cỏ dại mọc. Cũng thế, khi ta nhổ hết cỏ dại phải giâm giống lúa khoai, nếu để đất trống thì cỏ sẽ mọc lại. Trong khi cực lực chiến đấu với những phiền não, Phật tử không quên tăng cường tâm từ bi hỉ xả... vì đó là nước cam lồ để gột rửa những nghiệp cấu bợn phiền não đang khắn chặt trong tâm hồn ta. Và nó cũng là đám mưa tưới mát muôn loài đang bị lửa phiền não thiêu đốt.  
  
Tóm lại, trong ba món thanh tịnh, tư tưởng là quan trọng hơn cả, do đó người Phật tử tu đức thanh tịnh, xem tư tưởng là phần thiết yếu nhất, gạn lọc tư tưởng thanh tịnh rồi, ngôn ngữ, hành động tùy đó mà thanh tịnh. Như nước ở hồ lọc trong rồi, khi mở vòi nào cũng đều chảy nước trong cả.  
  
## Con người thanh tịnh hoàn cảnh cũng thanh tịnh {- #hoan-canh-thanh-tinh}

Một khi thân tâm ta thanh tịnh, hoàn cảnh sẽ tùy thuộc thanh tịnh. Hoàn cảnh không nhất định tốt, xấu, nhơ, sạch tùy hành động tư tưởng con người mà chuyển theo. Một nhóm người văn minh trí thức dù ở nơi thôn dã hoang vắng, nhưng một thời gian cảnh ấy sẽ trở thành tốt đẹp, thị tứ. Trái lại, một bọn người rừng chẳng hạn, cho ở giữa đô thành hoa lệ, một thời gian đô thành ấy sẽ biến ra cảnh nhớp nhúa xấu xa, nếu họ không được cải thiện... Bởi thế, đạo Phật muốn cải thiện xã hội, cải thiện quốc gia trước tiên phải cải thiện con người. Muốn cải thiện con người, đầu tiên phải cải thiện tư tưởng. Như vậy tư tưởng, ngôn ngữ và hành động con người thanh tịnh thì chính cõi Ta-bà này đã thành Tịnh độ rồi, hay thế giới này chính là thế giới Cực Lạc vậy. Ta muốn sanh về Tịnh độ, thì chính ta phải thanh tịnh trước đã. Kinh có câu:  

> Tam nghiệp hằng thanh tịnh, đồng Phật vãng Tây phương.

Nghĩa là:  

> Thân, miệng và ý hằng trong sạch, sẽ đồng như chư Phật sanh về cõi Phật.

Thế mà, có một số người ước mơ sanh về cõi Cực Lạc mà miệng vẫn nói ác, tâm vẫn tham, giận... thật là trái lẽ. Tu bằng cách đó chỉ làm trò cười cho thiên hạ mà thôi. Người Phật tử chân chánh không mơ ước gì hơn, ước mơ con người mình được thanh tịnh, không tranh đấu nào bằng tranh đấu với phiền não ở nội tâm. Thắng được phiền não, toàn thân đều thanh tịnh, thế là vạn vật tùy tâm, sống một cuộc đời tự do tự tại.  
  
Từ trên đến đây, đã thấy đức thanh tịnh là căn bản của người tu Phật, chẳng những căn bản của người tu, mà đức thanh tịnh cũng là cội nguồn của một xã hội văn minh; văn minh đúng với thật nghĩa của nó. Cho nên, bất luận trong đạo, ngoài đời nếu ai muốn cải thiện đời mình, cải thiện xã hội đều phải tu tập đức thanh tịnh cả... Nhưng gần nhất và cần yếu nhất là Phật tử, đã biết đi chùa, lễ Phật nghe kinh mà không áp dụng triệt để đức thanh tịnh vào đời sống của mình, thật là phản bội với tên Phật tử.  
