# Đức tinh tấn {- #duc-tinh-tan}

"Tinh" là chuyên, là thuần. "Tấn" là tiến tới. "Tinh tấn" là chuyên cần tiến tới theo một chiều hướng tốt đẹp, lợi ích, sáng suốt và an vui. Người Phật tử tu đức tinh tấn là tiến mạnh, tiến mãi trên con đường từ bi xa thẳm, dưới ánh sáng mặt trời giác ngộ. Ðức tinh tấn là một sức mạnh cả quyết, quả cảm, quét sạch, dẹp tan mọi trở ngại, mọi khó khăn để tiến tới mục đích tự lợi, lợi tha viên mãn. Nếu thiếu đức tinh tấn, con người sẽ là cánh bèo bấp bênh ngoài bể cả, là chiếc lá rơi lảo đảo theo chiều gió đưa!  
  
## Đức tinh tấn cần thiết cho con người {- #can-thiet}
  
Em là một học sinh, buổi tối nọ gặp bài khó, em ngồi đọc năm bảy lượt mà không vô đầu. Thối chí, em vươn vai vài cái, rồi ngáp! Thế là con ma lười biếng sáp nhập vào người em. Khi ấy nếu em không biết dùng ngọn roi thần "tinh tấn" đánh đuổi nó ra, em xếp tập lại, đi xổ mùng xuống rồi đánh ngon một giấc tới sáng. Thế là ngày mai, em phải bị thầy giáo quở phạt, chúng bạn chế nhạo. Một lần em đầu hàng ma "lười biếng", nhiều lần cũng thế, tức là đời em sẽ đi lần đến chỗ hư!  
  
Em là một Phật tử, hôm nay ngày chủ nhật, đúng 7 giờ em phải đi họp tại chùa, nhưng em nhớ những giờ lễ Phật phải quì, đứng trang nghiêm, giờ học giáo lý buồn buồn, em nghe hơi chán. Bỗng thằng Hỉ nhà bên cạnh lại rủ em đi xem chiếu bóng. Nó bảo: Sáng nay có xuất đặc biệt vào lúc 8 giờ, cuốn phim mới, hay, cười nôn ruột... Nếu không biết áp dụng đức tinh tấn vào lúc này, em sẽ theo bạn đi xem chiếu bóng. Ðó là em đã bị con quỉ "phóng túng" nhập xác và làm chủ em. Chủ nhật này em trốn, chủ nhật sau em lấy cớ nghỉ luôn... như vậy đời em dần dần sẽ xa lần ánh sáng đạo đức, mà bước gần về bóng tối trụy lạc!  
  
Ngoài ra, bác nông phu không tinh tấn là bỏ bê việc đồng áng. Anh công nhân không tinh tấn sẽ bị chủ đuổi có ngày. Một kỹ nghệ gia thiếu tinh tấn thì sự nghiệp không thành... 
  
## Kẻ thù của tinh tấn là ma "lười biếng" và quỉ "phóng túng" {- #ke-thu}

Con ma "lười biếng" nhập vào ai, người ấy tốt trở thành xấu, hay hóa ra dở, hiền lành trở nên hung dữ, sáng suốt biến thành ngu mê... Ngược lại, tinh tấn đến với ai, kẻ ấy hư hóa nên, xấu trở thành tốt... Nên tinh tấn và lười biếng chống nhau như tối và sáng, như trắng với đen. Có tinh tấn là không lười biếng, ngược lại cũng thế. Do đó, nên khi nào con ma lười biếng muốn nhập vào ta, ta phải cấp bách lấy roi thần tinh tấn mà trừ nó. Vừa thấy ngọn roi tinh tấn, bọn ma lười biếng đã chạy bay hồn.  

Con quỉ "phóng túng" lại càng nguy hiểm hơn. Chúng lôi người xuống hố trụy lạc, thúc đẩy người chạy rong trong rừng ngũ dục và sau cùng chúng dìm người trong bể trầm luân kiếp kiếp đời đời. Ngược lại, "tinh tấn" là cái móc kéo người lên khỏi hố trụy lạc, là kim chỉ nam hướng người trở về con đường sáng suốt, khỏi lạc trong rừng ngũ dục, là chiếc thuyền vớt người khỏi bể trầm luân và đưa lên bờ giải thoát. Vì thế, chúng đố kỵ nhau, không bao giờ chúng gặp. Nếu ai rước thần "tinh tấn" đến, thì "phóng túng" lánh xa, ngược lại cũng thế.  
  
## Tại sao ta phải tinh tấn? {- #tai-sao}

Chiếc thuyền người của chúng ta muốn về đỗ bến người và vượt lên bến Hiền, Thánh. Nhưng nó đang bị dòng nước lười biếng cuốn mạnh, ngọn gió phóng túng thổi đùa bấp bênh, sắp trôi về bể vô nhân phẩm. Nếu chúng ta không chuyên cần, không nỗ lực chèo chống nó về hướng đã định, thì nó sẽ chơi vơi phiêu bạt không bến đỗ, không chỗ nương, rồi một ngày kia đinh lay, ván mục, nó phải chìm lịm dưới đáy bể hư hèn. Ôi, còn đau đớn nào hơn, một kiếp người không định hướng! Vì thế, chúng ta phải tinh tấn và tinh tấn mãi mãi! Mỗi khi nhìn xuống con sông Cửu Long, thấy hình ảnh người chèo thuyền ngược dòng, trái gió, chúng ta nhớ đến đức tinh tấn, nguyện tiến mãi không ngừng.  
  
## Tinh tấn là một nghị lực {- #nghi-luc}

Trên đường thiện đâu phải toàn hoa và bướm mà rất nhiều hầm hố, chông gai; nếu người không quyết tâm dũng tiến rất dễ ngã lòng lùi bước. Em đã sống trong gia đình một hoặc vài năm, em đã thấy những trở ngại khó khăn trong việc hành đạo. Nhưng nếu em là một Phật tử chân chánh, em luôn thực hành theo hạnh tinh tấn, thì những cái trở ngại ấy, em thấy không đáng kể.  

Ðức Thích-ca ngót mười năm tìm đạo mà chưa toại nguyện, một hôm đến dưới cội bồ-đề, Ngài chỉ cội cây mà cả quyết rằng: *"Ngồi dưới cội cây này nếu tìm không được đạo, thì dù xương ta tan, thịt ta nát, ta nguyện không rời khỏi chỗ ngồi này!"*. Do sức cả quyết ấy, hay do đức tinh tấn đó, sau bốn mươi tám ngày, Ngài chứng thành đạo quả.  
  
Mỗi khi bị con ma lười biếng cám dỗ, con quỉ phóng túng rủ ren, các em nên theo gương đức Thích-ca mà cả quyết rằng: *"Trên đường đạo, đường thiện, dù tan thân mất mạng, ta không hề lùi bước!"*. Các em cương quyết được như vậy, bọn ma lười, quỉ phóng túng phải khiếp đảm le lưỡi chạy dài. Hằng ngày tập được đức tinh tấn mãnh liệt ấy, các em sẽ thấy giữa đời không có việc gì khó. Các em "muốn là được, quyết là thành". Ðời các em sẽ có nghị lực phi thường, không còn nhút nhát, hồi hộp, nghi ngờ như khi xưa nữa.  
  
## Kết quả của tinh tấn {- #ket-qua}

Phàm cái gì hễ có đi là phải có đến. Mà tinh tấn là tiến tới theo chiều hướng tốt đẹp, lợi ích và an lạc, nên kết quả của nó cũng toàn tốt đẹp và an lạc. Em học trò tinh tấn sẽ thành tài đạt đức. Người làm thợ tinh tấn sẽ trở thành một tay kỹ xảo. Phật tử hằng tinh tấn sẽ được đức hạnh đầy đủ, phước tuệ viên thành. Tóm lại, tất cả sự thành công trên đường tu thân sửa mình, trong việc thiện đều do tinh tấn quyết định. Bao nhiêu vị Hiền Thánh, bao nhiêu bậc giác ngộ đều do lò tinh tấn đúc nên.  
  
Tóm lại, từ trên đến đây, các Phật tử đã thấy tinh tấn là then chốt của đạo làm người, của đạo từ bi. Tinh tấn là một sức mạnh, là sự định đoạt đời người trên đường vinh quang, trong bầu không khí ngát hương thanh tịnh.
