# Người tu Phật có phải kẻ chán đời chăng? {- #nguoi-tu-phat-co-phai-ke-chan-doi-chang}

Có một số người muốn lên án đạo Phật, không biết gì hơn, họ mượn danh từ "chán đời" gán vào đạo Phật. Thế rồi họ oang oang lên rằng người tu là kẻ "chán đời", đạo Phật là đạo "chán đời"... Phản ứng lại, một số Phật tử nồng nhiệt bênh vực đạo, cực lực phản đối và đính chánh: "Người tu là yêu đời..." Chúng ta hãy gạt ngoài tình cảm, lấy lý trí xét đoán thử người tu Phật phải là "chán đời" không?  
  
Trước ta hãy định nghĩa "chán đời" là thế nào? - Theo nghĩa thông thường mọi người hiểu, "chán đời" là kẻ không bằng lòng xã hội thực tại.  
  
Có hai hạng "chán đời". Một hạng, vì không thỏa mãn tham vọng, bất lực trước cảnh trái nghịch đâm ra chán ghét xã hội. Một hạng vì thấy sự mục nát của xã hội, đủ khả năng cải đổi, nên chán cái cũ, xây dựng cái mới.  

Tỷ dụ: Có một cái nhà mục nát hư rách và bẩn thỉu, nắng không có chỗ ẩn, mưa không chỗ đụt, lại hôi hám thối tha. Trong nhà ấy có ba người ở. Người thứ nhất thì luời biếng, cho rằng số kiếp đã định, phải sao chịu vậy, rồi cứ đùa giỡn say sưa với cảnh đen tối ấy. Người thứ nhì, mỗi khi bị gió lồng mưa lọt thì chắc lưỡi hít hà, đâm ra căm tức muốn xô cho ngã, đập cho tan cái nhà oan nghiệt này, mà trong tay không có một đồng xu, một cây tre, một miếng lá... Người thứ ba nhận rõ sự khổ sở, sự bẩn thỉu, không cam chịu sống mãi trong cảnh tủi cực này, nhất định thay đổi cái nhà mục nát nhớp nhúa bằng cách dành dụm tiền, tìm vật liệu để xây dựng lại chắc chắn tốt đẹp, cho mình và anh em mình ở khỏi khổ.  

Ba anh em trong nhà này là đại biểu ba hạng người trong xã hội. Người thứ nhất là hạng người chạy theo dục lạc, không có một ý niệm gì về cuộc đời cả. Người thứ hai là hạng người chán đời, vì không thỏa mãn tham vọng và bất lực. Người thứ ba là hạng người tinh tấn, thấy sự mục nát của xã hội, chán cái cũ, xây dựng cái mới.  
  
## Hạng người chạy theo dục lạc {- #duc-lac}

Họ nói là yêu đời, kỳ thật họ chỉ yêu dục lạc mà thôi. Vùi mình trong dục lạc, họ chỉ sống có ngày nay mà không có ngày mai. Họ nhìn đời qua lớp sơn bên ngoài, nên say sưa mê mệt. Nếu ai nói cái gì khác hơn sự hưởng dục lạc, họ không ngần ngại gán cho danh từ "chán đời yếm thế". Ai khuyên họ làm lành lánh dữ, họ chế nhạo là lên mặt "thầy đời". Thấy ai khổ sở khuôn mình trong đạo đức, họ cười là bọn "dại khờ"... Mục đích của họ không ngoài thỏa mãn dục vọng nhất thời. Giá trị của họ là hưởng được nhiều khoái lạc. Bởi thế, nên cái nhìn, cái nghĩ của họ không quá một tấc, một gang. Và suốt đời không làm gì khác hơn là lo cho thằng người của họ. Thế mà, gặp ai họ cũng vỗ ngực ta đây là yêu đời. Hai tiếng "yêu đời" là cái bia danh dự nhất, để họ nêu lên trước quần chúng.  
  
## Hạng người chán đời vì không thỏa mãn tham vọng và bất lực {- #tham-vong}

Hạng người này nhìn đời bằng cặp mắt oán ghét, cuộc đời toàn xấu xa bỉ ổi, mọi người trong xã hội là kẻ thù của họ. Vì thế, họ muốn trốn một nơi nào, mà không có người bén mảng đến. Tại sao có quan niệm này? - Bởi vì:  
  
- Hoặc họ là người đã đổ bạc vạn để mua chức quan *(theo thời mua quan bán tước)* mà không đắc cử. Tiền đã sạch, của đã không thì còn gì mà không chán ghét xã hội.  
  
- Hoặc họ là một quan chức bị thải hồi. Khi xưa ra đường có kẻ võng người hầu, mà nay chỉ chiếc gậy quéo với cặp chân trần, thì tài nào họ không chán đời khinh bạc.  
  
- Hoặc họ là một thí sinh, bao nhiêu sinh lực đều dồn vào sự học; đến năm thi, đặt hết hy vọng vào cái cấp bằng để có sở làm, được cơm no áo ấm, thế mà thi trượt! Trượt một lần, hai lần... mắt họ đã hoa, nhìn trước cả một bầu trời đen tối.  
  
- Hoặc họ là người đang nặng lời biển hẹn non thề; bỗng không, ai đành ăn nguyền nuốt hẹn, để họ sớm hờn duyên, chiều tủi phận. Lòng uất hận tràn trề, họ thiếu suy xét, lầm tưởng mọi người đều xấu xa hèn mạt...  
  
Tóm lại, vì không thỏa mãn dục vọng, công danh v.v... nên đâm ra chán ghét đời. Những người này, không phải sẵn lòng chán đời, bởi họ tham cầu những cái gì trên đời mà không được, nên sanh hờn ghét. Nếu những điều họ muốn mà được như ý, thì họ còn mê đời hơn ai nữa.  
  
## Hạng người chán đời vì thấy xã hội mục nát, quyết thay cũ đổi mới {- #xa-hoi-muc-nat}

Hạng người này lòng thương không bờ bến, nhìn thấy sự lầm than đen tối của đồng bào, của nhân loại, quyết hy sinh đời mình để khỏa bằng những hầm hố chông gai, đưa nhân loại đến nơi vinh quang an lạc. Những vị điển hình của hạng người này:  
  
- Ðức Khổng Tử, vì chán cái xã hội mục nát của thời Xuân Thu nên quên nhọc nhằn, nay ở Lỗ mai về Vệ cho đến Tống, Trần... và chịu vất vả ngồi dạy học trò, biên chép kinh sách để mong vãn hồi Nhân đạo.  
  
- Ðức Jésus Christ, vì chán sự cai trị khắc nghiệt của người La Mã, chế độ giai cấp bất công của đế quốc Do Thái, nên không nệ vào tử ra sanh đi giảng đạo Bác ái.  
  
- Ông Tôn Văn, vì chán cái xã hội hủ bại của nhà Thanh, nên mới vận động cách mạng khởi nghĩa năm 1911 để thành lập Tam dân Chủ nghĩa.  
  
- Ðức Thích-ca, vì chán giai cấp bất bình đẳng của Ấn Ðộ thời ấy, chán lòng sân hận thù oán của loài người, chán cái si mê mù mịt của chúng sanh, nên vất bỏ cả ngai vàng ngôi báu, lìa vợ đẹp con yêu, ngót mười một năm tìm đạo trải qua nghìn vạn hiểm nguy. Sau khi đã thấy đạo, được phương pháp cứu khổ chúng sanh, Ngài dãi dầm sương nắng ngót bốn mươi chín năm, đem tinh thần bình đẳng thay cho giai cấp bất bình, lấy từ bi thay cho sân hận oán thù, dùng trí tuệ thay cho si mê mù mịt. Thế là, Ngài đã cải thiện xã hội bất công đen tối của loài người, trở thành xã hội lành mạnh tốt đẹp cho toàn thể dân sinh.  
  
Tóm lại, sống trong cảnh khổ mà không tự biết, cứ say sưa theo dục lạc khói mây là kẻ mù quáng. Ôm lòng tham trèo lên cây thang danh vọng, tài, sắc... rủi trượt chân đổ ngã, dập đầu toác trán, mới nhận ra nỗi khổ, nhưng chỉ biết kêu khóc, oán hờn là kẻ khiếp nhược. Nhận chân sự khổ rồi đem hết khả năng hoán cải xây dựng biến khổ trở thành lạc là bậc Thánh nhân, là người giác ngộ. Như thế, ta ngại gì không dám thừa nhận người tu là "chán đời", đạo Phật là "đạo chán đời". Chán để xây dựng, để đem hạnh phúc cho chúng sanh; chớ không phải chán để khóc than, thù hận như họ lầm hiểu.  
