# Thế nào là anh hùng? #{- #the-nao-la-anh-hung}

<div class="align-right">
> "... Chí những toan xẻ núi lấp sông,   
> Làm nên đấng anh hùng đâu đấy tỏ..."  
> -- *Nguyễn Công Trứ*
</div>
  
Bạn là một thanh niên, bạn có chí khí anh hùng, và bạn tưởng tượng bạn sẽ là anh hùng. Vâng! Bạn sẽ là anh hùng. Nhưng phải làm thế nào để thành một "anh hùng thật sự". Tôi nói anh hùng thật sự, để bạn khỏi lầm những anh hùng chỉ có tên, có tiếng, có oai ở bên ngoài.  
  
Ðể dễ bàn luận, chúng ta cần hiểu nghĩa căn bản của hai chữ anh hùng. Anh hùng là gì? - Anh hùng là người tài năng xuất chúng, công to, đức cả khiến mọi người đều kính phục.  
  
Thế mà giữa xã hội này, mỗi người quan niệm anh hùng theo mỗi cách. Do đó nên khi ngồi chung nhau thảo luận, thì mỗi người đều tự vỗ ngực xưng ta đây là "anh hùng".  
  
Bác Phó vào xóm rượu trà, cờ bạc tiền lưng hết sạch mà lại say sưa, ngã bờ té bụi. Về nhà vợ con cằn nhằn, bác lại nổi giận đùng đùng, trợn mắt phùng mang, đánh đập vợ con chạy tứ tán. Ra oai như vậy, bác thấy bác là anh hùng.  
  
Anh Hảo, trước mặt các cô thiếu nữ, anh vãi tiền như cát để mua một trận cười. Và lúc đó, nếu có ai bình phẩm hành động cuồng dại của anh, anh quyết một mất một còn tranh hùng với kẻ ấy, để cho những nàng tiên kia thấy chí khí và tài năng của anh. Ở trường hợp này, anh xem mạng sống nhẹ hơn bong bóng. Và dù phải lao mình vào hang beo, miệng cọp, anh cũng coi thường. Vì anh cho làm được như thế là anh hùng.  
  
Ông Bạo, vì tranh hơn thua việc làm ăn với bạn đồng nghiệp mà sanh cãi vã, ông nổi nóng chạy về nhà lấy bù lon, đến đập vào đầu người kia phun máu, rồi ông phải ngồi khám. Làm được vậy, ông cũng tự đắc mình là anh hùng.  
  
Cậu Tài, đắm mê tửu sắc, bỏ học hành, bị cha mẹ rầy mắng. Cậu tìm dao đâm họng tự tử. Thái độ đó, cậu thấy rất là anh hùng... Tóm lại, trong xã hội có vô số bọn "anh hùng rơm" như vậy.  
  
Ðến những kẻ có chút gan dạ, nhân thời loạn lập bè, kết đảng, cậy thế, ỷ quyền, tự xưng hùng, xưng bá, may ra được lúc đắc thời, đắc thế, họ sẽ vỗ ngực xưng ta đây là anh hùng. Ðó là nhóm "anh hùng thời cuộc".  
  
Sức mạnh của Lý Ngươn Bá, chuyển cặp chùy gần như lay trời, động đất, một tiếng hét muôn quân đều cúi rạp. Nhưng vì một cơn phẫn nộ không đâu, ông ném cặp chùy để tự sát. Tài cao chàng Lữ Bố, trước vạn quân không hề nao núng, giết kẻ địch như lấy đồ trong túi, thế mà vẫn đắm đuối vì sắc đẹp của Ðiêu Thuyền... Chinh phục hằng mấy triệu người, nhưng phải phủ phục trước một mỹ nhân, hay cơn phẫn nộ, là hạng "anh hùng sức khỏe".  
  
Lấy tiết nghĩa làm mục tiêu, giàu sang không thay lòng, lâm nguy không nhụt chí, thành công mà mất tiết nghĩa không màng, vong thân mà còn tiết nghĩa mới toại, đó là hạng anh hùng tiết nghĩa. Người điển hình cho hạng anh hùng này, ta thấy có Quan Vân Trường thời Tam quốc Trung Hoa. Vân Trường lúc ở với Lưu Bị cũng như khi về với Tào Tháo, lòng vẫn không đổi thay. Ðánh với Huỳnh Trung trăm hiệp không phân thắng bại, khi ngựa sẩy chân ném Huỳnh Trung xuống đất, Ngài liền dừng đao, không giết kẻ sa cơ. Tào Tháo là kẻ thù nguy hiểm, mà lúc thất thế lội bộ trong nẻo Huê Dung, Ngài cam chịu tội, để tha người cùng lộ. Cho đến đi đường cái, về đường cái, thà chết chứ không khiếp nhược. Những cử chỉ ấy, những thái độ ấy, Ngài đã hiển nhiên thành một vị anh hùng của Á Ðông. Nói về khỏe, Ngài đâu hơn Lữ Bố; nói về trí, Ngài sao bằng Khổng Minh. Thế mà, mọi người đều sùng thượng Ngài là vị Thánh, kính cẩn tôn thờ Ngài. Ngài là một vị anh hùng bất tử trong hiện tại cũng như suốt vị lai. Trong bài ca khen Ngài có câu:  

> "... Trung nghĩa tham thiên địa. Anh hùng quán cổ kim..."  
  
Ngài chỉ tiết chế phần nào lòng tham, để đưa đời Ngài đi theo chánh nghĩa, mà được mọi người quí chuộng dường ấy; huống nữa, người tiết chế toàn vẹn tham, sân, si để đem đời mình phụng sự cho nhân loại, thì cao quí biết ngần nào!  
  
Lão Tử nói:

> "Thắng nhân giả lực, tự thắng giả cường."  
  
Thực vậy, thắng người chỉ là vấn đề sức khỏe hay mưu chước xảo quyệt. Anh yếu tôi mạnh, tôi có thể lấn át được anh; anh thật thà chất phác, tôi mưu thần chước quỉ, tôi sẽ hơn được anh. Nhưng đó chỉ là vấn đề bên ngoài. Về nội tâm, một lần tôi hơn anh, là một lần tôi đã thua tôi. Vì anh yếu, tôi mạnh, tôi ỷ sức mạnh hiếp người yếu, đó là lòng "khinh mạn" đã làm chủ tôi. Anh thật thà, tôi xảo quyệt, ý trí khôn xảo của mình, tôi lường gạt anh, là tôi đã làm nô lệ cho lòng "tham lam". Tôi lấn át, lường gạt anh, anh thua tôi nhưng chưa hẳn là anh phục tôi. Ðể lòng "khinh mạn", "tham lam" làm chủ, tôi đã thật sự đầu hàng nó. Vì thế, thắng người chưa phải là mạnh.  
  
Thắng mình mới thật mạnh. Trước một vẻ đẹp yêu kiều, bạn giữ lòng không xao xuyến. Sắp nắm trong tay một mối lợi khổng lồ nhưng không hợp đạo nghĩa, bạn bỏ qua không chút hối tiếc. Ðời bạn hoàn toàn trong sạch mà bỗng nhiên một đứa thất phu vô cớ thóa mạ bạn, lúc đó bạn vẫn giữ lòng an tịnh không chút rạo rực... Những việc đó bạn nghĩ có dễ làm chăng? Người tầm thường có thể làm được không? - Chắc bạn cũng đồng ý như tôi, người thắng được lòng mình một cách quả cảm, đòi hỏi phải có một nghị lực phi thường, một bản lĩnh xuất chúng. Vì thế, người thắng được lòng mình mới thật là người mạnh.  
  
Ðây tôi giới thiệu bạn một phương pháp làm "anh hùng thật sự", "anh hùng muôn đời". Muốn làm vị anh hùng này, trước bạn phải tập tu đức nhẫn nhục. Nghe nói đến nhẫn nhục, bạn đã bật cười!... Khoan! khoan! Bạn đừng cười vội. Tôi biết bạn sẽ bảo: "Tôi thanh niên đâu phải như những ông già bạc nhược, mà mỗi cái bảo phải nhẫn nhục." Vâng! Bạn là thanh niên, nhưng bạn đừng lầm hiểu nhẫn nhục là hèn yếu khiếp nhược. Nhẫn nhục là một "khả năng chịu đựng". Có chịu đựng được mọi thử thách, mọi thống khổ, mọi bực dọc... người ta mới giàu nghị lực, mới đủ kinh nghiệm, mới tiến lên bậc Hiền, Thánh và xứng đáng là anh hùng.  
  
Một em bé ôm tập đến trường, nếu không chịu đựng nổi sự rầy phạt của ông thầy, em có thể biết chữ chăng? Một nhà thương mãi, nếu không chịu đựng được tiếng chê khen của khách hàng, những lỗ lã, nhà thương mãi ấy có làm giàu được không? Một kỹ nghệ gia, nếu không chịu đựng được sự hư hao thất bại, sự thắc mắc của nhân công, có thể lập nên những xí nghiệp vĩ đại chăng?... Tóm lại, ở giữa xã hội này, trong mỗi ngành, mỗi nghề, nếu người không có sức chịu đựng, thì không làm được việc gì cả.  
  
Chịu đựng được ngoại cảnh chưa phải khó, chịu đựng được nội tâm mới thật ngàn lần khó hơn. Tôi đang ngồi chơi, vô cớ một người đến thóa mạ tôi. Khi ấy, tôi chửi mắng lại họ là khó? Hay tôi giữ lòng phẳng lặng không cho cơn giận dấy lên là khó? Người chửi mình, mình chửi lại, việc ấy trẻ con lên ba cũng thường làm. Người chửi mình, mình vẫn giữ thái độ bình thản, lòng không rạo rực, mới thực khó. Ðiều này, chỉ những bậc Thánh nhân, những hạng anh hùng mới làm được. Muốn làm anh hùng, bạn phải làm những việc các bậc anh hùng đã làm. Còn việc hàng ngày của trẻ con ấy, bạn nên tránh xa; nếu bạn làm theo, bạn đã trở thành trẻ con nốt!  
  
Chắc bạn sẽ băn khoăn hỏi tôi: Tại sao các bậc Thánh nhân chịu đựng được những cái khó chịu đựng ấy? - Thưa bạn, bởi các Ngài dồi dào nghị lực, sáng suốt nhận định lẽ phải nên chịu đựng rất dễ dàng. Bằng chứng, đức Thích-ca một hôm đang giảng đạo, bỗng một kẻ ngoại đạo đến nhục mạ Ngài. Ngài yên lặng không đáp, gương mặt tươi tỉnh như không. Nói mà không người đáp, khác nào nhóm lửa giữa hư không, kẻ ngoại đạo bực tức hỏi Ngài:  

\- Tại sao tôi nhục mạ ông, mà ông không trả lời?  

Phật ung dung đáp:  

\- Này ngươi! Ngươi đem một món quà đến cho ta, ta không nhận, món quà ấy về ai?  

Người ngoại đạo đáp:  

\- Tôi cho ông, ông không nhận là về tôi.  

Phật bảo:  

\- Cũng thế, ngươi nhục mạ ta, ta không nhận thì ngươi tự chuốc họa vào mình.  
  
Một hôm đi dạo phố, bạn gặp người điên rượt đánh bạn. Trường hợp đó, bạn nghĩ sao? Ðánh lại họ chăng, hay chạy tránh họ? - Nếu bạn nhận bạn là người trí, bạn chỉ yên lặng lánh xa họ. Vì họ đã là điên mà mình chống cự họ, mình cũng điên nốt. Cũng thế, giữa đời này những kẻ gây sự vô cớ, khác nào người điên kia. Ta là người trí nên tránh họ, mà không nên chống đối.  
  
Người tu đức nhẫn nhục không những chịu đựng những cơn phẫn nộ không cho dấy khởi, mà bất cứ điều gì làm cho tâm hồn xao xuyến rạo rực đều chịu đựng để dằn ép chúng trở về trạng thái yên tĩnh. Nhẫn nhục là một cách súc tích khí lực điều khiển thân tâm mình. Người làm chủ được mình là một sức mạnh vô biên. Phật dạy:  

> "Thắng một vạn quân, không bằng thắng mình. Thắng mình mới là chiến công oanh liệt."  
> <div class="align-right">-- *(Kinh Pháp Cú)*</div>
  
Người đời chỉ mong chinh phục kẻ khác, chinh phục ngoại cảnh mà quên đi nội tâm. Khác nào con trong nhà không dạy, không răn, mà đi dạy răn con người hàng xóm, thật là một việc viển vông. Bắt nạt người cung kính, tuân lệnh mình, mà mình nô lệ thất tình lục dục, thì còn tai hại nào to hơn! Ông A có uy quyền, có thế lực, ai cũng sợ, cũng khiếp, bảo điều gì ai cũng phải theo. Như vậy nếu ông A bị nô lệ lòng tham, chúng ta thử nghĩ, những kẻ dưới tay ông sẽ là gì? - Phải chăng sẽ là những con chó săn đang lao mình trong rừng rậm. Trong xã hội này, nếu ai cũng muốn tạo uy quyền bên ngoài, mà không thắng được bên trong, thì xã hội sẽ ra sao?  
  
Tóm lại, tạo uy quyền bên ngoài tuy khó, nhưng đã lắm người tạo được. Ðiều phục nội tâm là chuyện khó gấp bội lần hơn, chỉ những bậc Thánh nhân, những vị anh hùng mới làm được. Vì thế, đức Thích-ca chưa từng cầm gươm lên ngựa chinh phục một ai, chỉ ngồi tĩnh tọa dưới cội bồ-đề, chuyên gạn lọc nội tâm, mà Ngài đã được hiệu "Ðiều Ngự Sư" hay đấng "Ðại Hùng Ðại Lực". Ngài là một vị "Anh hùng muôn đời". Tôi mong bạn, một thanh niên của nước Việt Nam, bạn hãy đắn đo cẩn thận, trước khi bạn tập làm "anh hùng".  
