# Phương pháp lập nghiệp vĩnh cửu {- #phuong-phap-lap-nghiep-vinh-cuu}

Ðã làm người, ai không muốn lập công danh hiển hách, sự nghiệp vẻ vang để lưu truyền vạn đại. Sự ước mong là thế, nhưng trên đường lập nghiệp đã biết bao người, hoặc đuối sức quằn quại tắt thở bên vệ đường, khi nhìn thấy thành trì sự nghiệp còn xa lắc; hoặc đã rỗ chân, sầy trán mà tìm không thấy bóng thành trì sự nghiệp ở đâu, rồi âm thầm nuốt hận quay về với hai bàn tay trắng và gương mặt hốc hác héo sầu. May ra, cũng có vài người đến thành sự nghiệp, nhưng khi đến nơi nó đã trở thành giả ảnh tan theo như sương mù buổi sớm, bọt nước chiều hôm.  
  
Tại sao có những cuộc dở dang và thất bại ê chề trên con đường tìm sự nghiệp?  
  
Là vì động cơ lập nghiệp của người đời là lòng tham, mà lòng tham không bờ bến, còn sức người có chừng; nên chi đều thất vọng. Người ôm lòng tham chạy tìm sự nghiệp, thì ôi! Khác gì kẻ mang kiếng xanh soạn tìm tờ giấy trắng, biết bao giờ gặp được. Ngày xưa có một nhà vua muốn xem thử lòng tham của người lên đến đội nào. Ông ra lệnh cho một lực sĩ rằng: "Từ mai sớm khi mặt trời hừng mọc, cho đến chiều hôm khi mặt trời vừa lặn, ngươi chu vi đất được bao nhiêu ta sẽ cho ngươi hết." Chàng lực sĩ hớn hở lui về, dự bị lương thực dùng một ngày. Hôm sau vừa sớm tinh sương, chàng chực sẵn trước đền vua. Mặt trời vừa ló dạng, chàng cắm đầu chạy. Chàng chạy hăng quên cả cơm nước. Mặt trời đã đứng đầu, chàng nhìn quay lại thấy khu đất còn nhỏ xíu. Bóng đã ngả dài, tranh thủ với thời gian, chàng chạy nhanh hơn, cho đến thân hình chàng chỉ còn là một vật chao động dưới bóng mặt trời. Vầng ô vừa kề đầu núi, chàng vận dụng hết tàn lực chạy cho đến đích, khi mặt trời vừa lặn. Ðến đích, thì ôi! Chàng chỉ còn là một xác không hồn.  
  
Lại nữa, nền móng và nguyên liệu xây cất sự nghiệp, người đời đã đặt và dùng sai lầm, nên chỉ sớm đổ vỡ. Tòa lâu đài sự nghiệp họ đặt trên vũng bùn tham lam, nguyên liệu xây cất tòa lầu ấy, toàn bằng xương và máu thì làm sao thành tựu vững bền được! Bằng chứng, sự nghiệp của Tần Thủy Hoàng ở Trung Hoa hồi thế kỷ thứ III rất to tát và vĩ đại, nhưng kết tinh bởi lòng tham lam và xây đắp bằng xương máu của muôn dân, nên chi ông cố tìm mọi phương thế để gìn giữ nó, mà rốt cuộc cũng không trường tồn. Ðến công nghiệp vẻ vang và oai hùng của Napoléon ở Pháp vào đầu thế kỷ XIX, cũng do động cơ tham lam vô bờ bến của ông. Muốn thôn tính hết các nước Âu châu, nên công nghiệp ấy chóng tàn như hoa phù dung buổi sáng, và sau cùng ông bị an trí tại đảo Sainte Hélène. Lại giữa thế kỷ XX, sự nghiệp rực rỡ nhất thời của Hitler đã làm vang động thế giới, nhưng cũng bởi lòng tham muốn làm bá chủ thế giới, nên ước nguyện chưa thành mà đời ông đã mai một... Có câu: *"Xây dựng sự nghiệp mình trên xương máu của người chỉ là mầm tan hoại."*  
  
Như trên đã thấy, càng tham lam bao nhiêu thì càng chóng tan hoại và đổ vỡ bấy nhiêu. Vậy chúng ta không nên dùng động cơ tham lam gây dựng sự nghiệp, mà cần phải lấy nguyên liệu từ bi đắp xây thành trì sự nghiệp thì mới kiên cố và trường tồn. Bởi vì kẻ tham lam muốn lập nên nghiệp cả, bao giờ cũng chăm lòng tóm thâu vơ vét của người về mình, mà tóm thâu vơ vét càng nhiều thì gây oán, kết thù càng lắm. Ðã có oán thù, là có người manh tâm phá hoại, rồi một người cố giữ gìn, mà cả nghìn muôn người quyết phá hoại, thì dù gian hùng như Tào Tháo, mưu trí như Khổng Minh cũng không tài nào giữ nổi. Ngược lại, lấy từ bi làm động cơ lập nghiệp, tức là lấy sự ban ân bố đức cho người làm sự nghiệp mình. Tuy nhiên đem tiền của và hạnh phúc mình tung vãi cho người là đời mình sẽ thấy khổ sở và thiếu thốn; nhưng một nụ cười nở trên môi người đói khát khi được chén cơm, một cái nhìn tri ân của người vừa thoát nạn, một cái chào cảm mến của người lạc lối khi được đưa đường... bấy nhiêu ấy là nguồn hạnh phúc vô biên, là của tiền vô lượng của chúng ta vậy. Sự nghiệp ấy mới nhìn qua như không có, nhưng kỳ thật nó có rất nhiều. Bởi vì, thói thường người đời hễ thương mến ai thì muốn ủng hộ, bảo vệ cho người ấy được an vui. Chúng ta đã gieo rắc tình thương khắp mọi người thì sự an vui đến với chúng ta vô lượng. Thế là sự nghiệp vĩ đại và vĩnh cửu chớ gì!  
  
Hơn nữa, người có lòng từ bi không thấy hạnh phúc với sự nghiệp riêng mình, mà chỉ thấy hạnh phúc với sự nghiệp chung của tất cả chúng sanh. Như vậy, càng gây cho chúng sanh được nhiều hạnh phúc, nhiều sự nghiệp, thế là hạnh phúc và sự nghiệp mình càng to. Ðức Thích-ca xa lìa đài vàng ngôi báu, chối bỏ tất cả hạnh phúc riêng, Ngài chỉ ôm bình bát đi xin ăn để gieo rắc tình thương và cảm hóa nhân loại. Do đó, mà khắp năm xứ ở Ấn Ðộ thời ấy, từ vua chúa đến quan dân đều tôn kính Ngài là bậc Từ phụ, sẵn sàng hiến dâng những ngôi vườn đẹp đẽ, để Ngài làm nơi giảng đạo. Cho đến ngày nay cách Phật đã trên hai mươi lăm thế kỷ, mà hầu khắp các nước trên thế giới đã xây cất biết bao ngôi chùa nguy nga tráng lệ để phụng thờ Ngài và trên sáu trăm triệu người kính thành, tôn Ngài là đấng cha lành. Nên trong kinh có câu: *"Xả tất cả sẽ được tất cả"* là thế.  
  
Tóm lại, chúng ta phải sáng suốt không nên nhìn thiển cận ở sự nghiệp nhất thời mà bị lòng tham lam sai sử, rồi cả đời luống lao tâm tiêu tứ, kết quả chỉ chuốc lấy đau khổ. Chúng ta phải tung vãi hạnh phúc mình cho mọi người, gieo rắc tình thương cùng khắp nhân loại, ấy là thứ hạnh phúc chân thật, sự nghiệp vĩnh cửu của mình đấy. Một Phật tử đã biết áp dụng điều này, Vua A-dục, nói: *"Ta xem hạnh phúc của chúng sanh là mục tiêu thứ nhất ta phải tranh đấu."*  
