# Gian lao không làm ta nhụt chí {- #gian-lao-khong-lam-ta-nhut-chi}

Bạn với tôi là cùng màu áo, chung thờ một lý tưởng. Ðã lâu chúng ta không gặp nhau, hoặc đã gặp mà không có dịp trao đổi ý kiến cùng nhau. Hôm nay ngày hoan hỉ đã về, lòng tôi thấy nao nao, nhớ đến bạn và cần nhủ đôi lời cùng bạn, gọi là thực hiện phần nào điều kiến hòa đồng giải của đức Từ Phụ đã dạy chúng ta.  
  
Bạn ạ! Trên đường học đạo thật xa diệu vợi, chúng ta tiến bước đã dẫm phải bao mũi gai nhọn cản trở, và hiện thăm thẳm những hố sâu, sừng sững những vách đá chơi vơi chặn lối đi của chúng ta. Ở trường hợp này, bạn xử trí thế nào? Lùi lại chăng? Hay hăng hái tiến tới? Chắc bạn sẽ đồng thanh với tôi, chúng ta không thể lùi lại, mà vẫn anh dũng tiến lên, vì đó là hướng ta nhắm. Bảo thành đã hiện trước mắt ta rồi, dù phải tan thân mất mạng, chúng ta cũng được hài lòng, vì cái chết đó làm tăng thêm giá trị ta và đưa ta vượt lên một nấc khá cao trên cây thang đạo hạnh.  
  
Bạn thử nghĩ! Những học sinh trung học, sinh viên đại học chịu biết bao khổ sở do những cuộc thi hành phạt. Có đôi khi, họ phải gạt nước mắt, cho đến muốn tự tử là khác. Như vậy người bày ra cuộc thi, phải chăng vì muốn ngăn bước tiến của họ? - Nhất định là không. Ðó là những cuộc thử thách để khuyến khích họ cố gắng thêm, là cây thước để đo trình độ và khả năng của họ, cũng là làm tăng giá trị của họ vậy. Nếu một sinh viên đủ lý trí, có sợ thi khó mà bỏ học chăng? Có cưu lòng oán hận người khảo hạch mình không? - Chắc là không, họ sẽ mang ơn những người khảo hạch, vì nhờ đó mà họ tiến thêm.  
  
Lại nữa, một chiến sĩ, vì bảo vệ non sông tổ quốc và rạng danh cho giống nòi, nên xem thường chết sống, lăn mình vào rừng bom đạn. Nếu một chiến sĩ mặc bộ nhung phục bóng láng, cỡi con bạch mã thật xinh, mỗi khi ngồi trên lưng ngựa xem rất oai vệ, nhưng suốt đời chỉ ăn với ngủ, thì còn gọi được là "chiến sĩ" chăng? Cố nhiên, người chiến sĩ muốn được ngày khải hoàn rực rỡ: mỗi nhịp ngựa là hằng vạn tiếng hoan hô, hoa bội tinh bừng nở trên ngực, trước muôn triệu cặp mắt nhìn quên nháy và ước mơ, thì phải lăn mình trong ngàn tên muôn giáo, xem cái chết nhẹ hơn làn gió thoảng. Như vậy, những nguy hiểm gian lao đối với người chiến sĩ anh dũng sẽ không thấy gian lao mà chỉ thấy là công danh sự nghiệp.  
  
Bạn ạ! Chúng ta là người chèo thuyền ngược dòng đời, thì làm gì có sự dễ dàng bình thản. Giả sử có, thì mục đích chúng ta nhắm đâu còn cao quí, vì mọi người đều có thể đến được. Bạn thử tưởng tượng, nếu một tu sĩ ăn no, ngủ kỹ, đầy đủ mọi nhu cầu, mãi sống trong cảnh nhàn hạ, mà được thành Phật, thì ông Phật ấy còn ai chịu lạy chăng? - Chắc là không! Vì dễ làm quá, có gì khó khăn mà phải kính phục. Sở dĩ chúng ta và mọi người đều tôn sùng kính lạy đức Phật, vì Ngài làm những điều mà chúng ta chưa làm được. Như vậy, giá trị người tu có là do vượt qua mọi hiểm trở khó khăn, ở chỗ ô trọc, mà tâm vẫn thanh bạch cao khiết.  
  
Bạn đang tu hạnh nhẫn nhục chăng? Nếu bạn tu hạnh nhẫn nhục, mà không có người mạ nhục, đánh đập để thử lòng bạn có phiền, có giận chăng? Thì cái nhẫn nhục ấy chỉ là nhẫn nhục ở đầu môi. Muốn chứng thật hạnh nhẫn nhục của bạn, phải có người mạ nhục, đánh đập: ấy là lửa thử vàng nhẫn nhục của bạn vậy. Ðức Thích-ca khi còn làm vị tiên tu nhẫn nhục, nhờ có vua Ca-lợi cắt tay, thẻo mũi... Ngài mới chứng được nhẫn nhục Ba-la-mật.  
  
Bạn đang tu hạnh bố thí chăng? - Thế là những kẻ đến xin đều là ân nhân của bạn. Nếu thiếu họ, bạn sẽ không viên mãn công hạnh. Mặc dù trong số người xin cũng có một hai kẻ đèo bòng, xin những điều không thể cho được. Nhưng bạn đừng vội phiền họ, mà bạn phải tự trách mình hạnh bố thí chưa cứu kính. Người Bà-la-môn xin con Thái tử Tu-đại-noa, chính là người đã giúp Ngài thành tựu hạnh bố thí Ba-la-mật, các hạnh khác cũng thế.  
  
Tất cả cuộc thử thách đều là sự chứng thật hạnh tu hành của mình. Người hay hoàn cảnh để thử thách ta đều là ân nhân, là cảnh tốt nâng đỡ ta lên từng lầu thánh nhân. Vì thế trong kinh Pháp Hoa, đức Phật đã nói:  

> "Ðề-bà-đạt-đa là thiện hữu tri thức bậc nhất của ta, nhờ Ðề-bà-đạt-đa mà ta mau chứng quả Vô thượng Chánh đẳng Chánh giác."  
  
Như trên bạn đã thấy, cái "khó" không phải là điều làm nhụt chí ta, mà là sự nghiệp, là chứng thật đời tu của ta. Càng gian lao, càng khó khổ, chiến thắng được nó thì giá trị ta càng cao, sự nghiệp ta càng lớn. Vì thế, các vị Bồ-tát hy sinh cảnh Niết-bàn để vào địa ngục cứu độ chúng sanh.  
  
Chúng ta đã là người tu, người sẵn sàng chịu khó khổ, mọi thử thách để rèn luyện lòng mình, để thay khổ cho chúng sanh, thì bao giờ có thở dài khi gian lao, chau mày khi nguy hiểm... mà nhất định tươi tỉnh hăng hái tiến thẳng đến mục đích tuyệt vời của mình đã nhắm. Ấy là con đường mà tôi và bạn cùng đi, cùng hướng. Vậy chúng ta sẽ hẹn ngày để gặp nhau ở điểm cứu kính này.  
