# Thanh niên với việc đi chùa {- #thanh-nien-voi-viec-di-chua}

Hôm nay đem việc đi chùa mà bàn với các bạn thanh niên thật là một chuyện rất tầm thường. Thưa bạn! Tôi lại thích nói những chuyện tầm thường ấy, vì nó rất gần chúng ta, mà đã bị nhiều người lãng quên đi.  
  
Nếu một hôm có người đến mời bạn đi chùa, chắc bạn sẽ cau mày lộ vẻ khó chịu, nếu không bĩu môi kiêu ngạo. Vì bạn thanh niên cho việc đi chùa là việc của những người giàu lòng tín ngưỡng, việc của bà già, ông cụ, còn thanh niên là những con người khoa học thực tế mà ai đi làm việc ấy. Quan niệm đó có thể đúng với người không hiểu ý nghĩa đi chùa, e không đúng với những người đã hiểu ý nghĩa đi chùa.  
  
Thưa bạn! Trong nhà Phật mỗi việc làm, mỗi hành động đều có ý nghĩa của nó, đáng tiếc có một số tín đồ không chịu tìm hiểu, nên việc làm sai lạc, gây sự hiểu lầm cho khách bàng quan. Vì thế, tôi cần biện bạch ý nghĩa đi chùa để các bạn biết qua.  
  
Ði chùa có những ý nghĩa:  
  
Chùa là nơi thờ cốt, tượng của chư Phật - người từ bi và giác ngộ đã viên mãn. Phật tử đến chùa là tỏ lòng kính mến, sùng thượng gương cao cả của Ngài mà học đòi bắt chước theo, như châm ngôn ta có câu: *"Trọng thầy sẽ được làm thầy"* vậy. Bạn một phen bước chân đến cổng chùa là trong ký ức bạn đã quay lại đức hy sinh cao cả, gương trí tuệ sáng ngời của Phật Tổ rồi. Bước vô chánh điện, nhìn lên chân dung của Phật, bạn sẽ thấy cặp mắt hiền lành, vẻ mặt từ bi của Ngài hình như lúc nào cũng chực đưa tay cứu vớt chúng sanh đang đắm chìm trong đau khổ. Chỉ chừng ấy thôi, bạn cũng đã thấy hình dáng Phật gây cho bạn một ấn tượng tốt lành, một gương sáng cao quí. Bạn đi đến chùa để nhớ lại công hạnh vị tha không bờ bến, đức độ hỉ xả vô biên giới của Phật mà bắt chước theo, chớ đâu phải đi chùa để lễ bái, để khấn nguyện. Như các nhà ái quốc hằng đến thăm lăng, miếu các công thần. Không phải các ông đến đó để xin xăm, để khấn vái, cầu sự ủng hộ cho mình, mà để ôn lại cuộc đời oanh liệt của các Ngài qua những tấm bia, chiếc mão... cho lòng ái quốc của mình được nồng nhiệt thêm.  
  
Phật thuyết pháp hơn ba trăm hội, những lời vàng ngọc ấy được ghi chép lại thành ba tạng kinh điển, trong ấy chứa đựng một nền triết lý cao siêu, một biển từ bi bát ngát. Bạn đến chùa để học hỏi giáo lý, qua lời chỉ dẫn của các nhà sư. Vì bạn là một thanh niên Việt Nam, bạn không thể chối cãi được ảnh hưởng ít nhiều của đạo Phật, một đạo cổ truyền của dân tộc mà người Việt Nam đã nhìn nhận là đạo ông bà. Hơn nữa, đạo Phật là một tôn giáo lớn nhất, một nền triết lý cao nhất của Á Ðông, bạn là một thanh niên trí thức Á Ðông, không có lý do gì bạn không biết. Nếu bạn nói không biết thì chẳng hổ với những học giả Âu Tây đang hướng về Á Ðông để nghiên cứu ấy sao? Hoặc bạn viện lẽ: *"Tôi ở nhà đọc sách Phật thì cũng hiểu được, cần gì phải đi đến chùa."* Thưa bạn! Ðiều ấy chưa hẳn là đúng. Vì sao? Vì bạn đang bận sự học hành hoặc đang lo sanh kế, thời giờ đâu bạn nghiền ngẫm kinh sách, nếu có thời giờ thì cũng rất eo hẹp. Chắc bạn cũng thừa hiểu kinh điển của nhà Phật như biển cả bao la, nền triết lý Phật giáo như trời cao thăm thẳm. Muốn thấu hiểu, người ta phải chuyên học cả năm, mười năm mà chưa hẳn là đã đạt được; phương chi nằm nhà đọc qua vài ba quyển sách mà có thể thấu triệt được ư? Lại nữa, thà rằng bạn không hiểu gì về Phật giáo còn hơn là bạn hiểu không đúng chân tinh thần của Phật giáo. Vì sự hiểu sai lạc sẽ làm giảm giá trị của Phật giáo và gây cho những người chung quanh một quan niệm sai lầm, nên không hiểu thì thôi, có hiểu cần phải hiểu cho đúng. Do đó, muốn hiểu Phật giáo, bạn cần đến chùa nhờ những vị sư học rộng giáo điển giảng dạy cho, có phần bảo đảm hơn.  
  
Trong những ngày đem hết tâm lực tranh đấu với đời, bạn nghe đầu óc nóng ran, tâm trí quay cuồng, bạn muốn tìm một nơi giải trí cho nó êm dịu lại. Hoặc bạn đến rạp chiếu bóng. Ở đây bạn thấy nghẹt cả người, hơi người đã khiến bạn nghe mệt. Nếu cố gắng mua vé vào cửa, bạn cũng thấy trên màn bạc toàn là sự tranh đấu, giết chóc, khổ vui, rốt cuộc chỉ làm cho thần kinh bạn thêm căng thẳng. Hoặc bạn đến nhà hàng để tiêu khiển bằng những chung rượu, chén trà. Nhưng vừa ngồi lại, bạn đã nghe lời bàn bạc, tiếng cãi vã về hơn, thua, khôn, dại của những người lân cận, khiến bạn phải nhức đầu. Như thế cũng là một trường tranh đấu, tranh đấu bằng lý thuyết. Bạn sẽ đến và đến nhiều nơi nữa, nhưng ở đâu rồi cũng gây thêm cho bạn một ý niệm so sánh, tranh đấu. Chi bằng, bạn đi thẳng đến chùa, không khí ở chùa sẽ ru êm, xoa dịu tâm hồn bạn. Ở đây, bạn sẽ thấy cả một trời thanh tịnh. Cổng chùa rêu xanh phủ kín, mặc cho nắng táp mưa sa, ngôi chùa đứng lặng im trong không gian tịch mịch. Có nghe chăng, chỉ những tiếng gió thì thào trên ngọn dương như lời giảng đạo của đức Mâu-ni hơn hai nghìn năm còn vọng lại, tiếng chuông ngân nga nhịp nhàng hòa theo gió, rồi tan lần trong không gian lặng lẽ như đem lòng từ bi chan rải khắp trần gian và tiếng Mô Phật - thay cho lời chào - của các nhà sư vừa hiền hòa, vừa thanh thoát. Ở đây, bạn không làm gì tìm ra được một dấu vết tranh đấu, nếu có chỉ là sự đấu tranh nội tâm của những con người cầu tiến. Sau vài mươi phút ở chùa, dù tâm hồn bạn có cuồng nhiệt đến đâu cũng tan biến dần trong không gian tĩnh mịch như ngọn lửa hồng đang cháy sẽ tắt lịm đi sau một cơn mưa mát dịu.  
  
Hoặc trong những lúc chạy đua với đời, bạn đã gặp phải những bức tường chắn lối, hoặc bị sa chân vào cạm bẫy của đời, bạn đang hằn học, đau buồn. Bạn cứ đi ngay đến chùa vì ở đây là nguồn an ủi vô biên của chúng sanh, là suối nước cam lồ để diệt trừ nhiệt não. Vào chùa, bạn sẽ thấy đức Thích-ca trang nghiêm ngự trên đài sen, đức Di-lặc tươi cười thản nhiên trong khi bị bọn lục tặc chọc tai, móc miệng... , đức Di-đà kiên nhẫn sẵn sàng đưa tay chực cứu độ chúng sanh, trong khi chúng vẫn còn lặn hụp trong biển ái. Qua những hình ảnh ấy, bạn đã thấy thế nào? Và gợi cho bạn những cảm giác gì? Ðức Phật Thích-ca ngự trên đài sen là đã nói: *"Ngài dấn thân trong trần tục mà vẫn trong sạch, siêu thoát, không bị mùi trần tục làm nhiễm ô"*. Ðức Di-lặc cười thản nhiên, trong khi bọn lục tặc phá phách, để nói rằng: *"Ngài sẵn sàng tha thứ, vui vẻ tha thứ và mãi mãi tha thứ tất cả những cái gì mà chúng sanh đã làm cho Ngài rối rắm, đau khổ"*. Ðức Di-đà đang duỗi tay cứu độ chúng sanh, mà chúng sanh chưa hướng về Ngài, để nói lên rằng: *"lúc nào Ngài cũng kiên trì cứu độ chúng sanh, mặc dù chúng đang còn mải mê theo trần tục"*. Và còn, còn rất nhiều hình ảnh nữa, tôi không thể kể hết. Nếu bạn biết rõ ý nghĩa khi qua những hình ảnh ấy, bạn sẽ nghe cõi lòng mát lại, quả tim bạn đập đều và bao nhiêu nỗi buồn phiền đã tan biến tự bao giờ.  
  
Ðó là chưa nói bạn có diễm phúc thấm nhuần giáo lý. Nếu bạn có duyên lành, gặp một nhà sư đức hạnh, bạn sẽ được tắm mát trong dòng suối từ bi, bạn sẽ bừng tỉnh dưới ánh sáng giác ngộ qua lời giảng giải của nhà sư rút trong giáo điển. Thế là, còn sự buồn phiền nào đeo đẳng trong tâm hồn bạn mà không tan vỡ?  
  
Cho nên đi chùa không phải chỉ vì sự cúng lạy khẩn cầu, mà để noi theo gương lành của Phật, cải đổi tự thân, để học hỏi giáo lý, tu sửa tâm tánh, để lắng lặng tâm hồn khi đang quay cuồng vì đấu tranh, để xoa êm, tưới dịu phần nào ngọn lửa tức giận, vết thương đau khổ.  
  
Cũng có người viện lẽ rằng: *"Tôi ở nhà, tôi vẫn thờ Phật để học theo gương Ngài, tôi cũng xem kinh để tu sửa tự tâm... thì còn hơn đi chùa."* Ðành rằng ở nhà có thờ Phật, có xem kinh, nhưng làm sao bằng khung cảnh trang nghiêm ở chùa, lời nhắc nhở chân thành của các nhà sư. Chúng ta chưa phải là bậc "sanh nhi tri chi" thì cần phải nhờ thầy lành bạn tốt, hoàn cảnh thuận tiện làm trợ duyên bên ngoài, mới đủ sức cải đổi những cái xấu dở của mình.  
  
Hoặc người ta không chịu đi chùa bởi những lý do:  
  
Vì cửa từ bi quá rộng cho nên có một ít người lợi dụng đó làm kế sinh nhai, hoặc để giấu những hành tung đê tiện. Do đó đã xảy ra nhiều việc không hay, làm hoen ố chốn thiền môn thanh tịnh. Vì vậy, có một ít người sợ đến chùa bị lợi dụng hoặc bị xấu lây. Thưa bạn! Bất cứ một tôn giáo, một đoàn thể nào cũng có những con chiên ghẻ lẫn trong ấy. Nếu bạn vì thấy một vài cái dở mà chấp nê thì tránh sao khỏi cái lỗi "vơ đũa cả nắm". Hơn nữa, bạn là người có học thức, một hành động, một cử chỉ bất chánh bạn đã thấy, tội gì bạn phải sợ như vậy.  
  
Hoặc có người nói: *"Ðến chùa nghe những điều tội phước, thấy gương từ bi của Phật sợ về nhà chán ngán việc làm ăn - việc làm ăn lợi mình hại người - nên không dám đi chùa."* Nói thế là cùng! Bạn thử nghĩ, có ai sợ người ta chỉ lọ trên mặt mình không? Nếu được người ta chỉ cho mình, có lợi hay có hại? Nếu vì lý do như vậy mà không đi chùa thì tôi cũng không biết lời gì mà bàn được.  
  
Nói thế cũng đã dông dài rồi. Ðể kết thúc lại, ý nghĩa đi chùa là để gợi lại cho chúng ta thấy những gương sáng cao cả để mở rộng kiến thức, để gội rửa những bụi nhơ phiền não, để xoa dịu những vết thương đau. Sự đi chùa như vậy có gì là huyễn hoặc nhuộm mùi mê tín, không thích hợp với óc khoa học thực tế của thanh niên đâu? Theo tôi thiết nghĩ: Các bạn thanh niên phần nhiều tâm hồn sôi nổi bồng bột, thiếu đức bình tĩnh, thiếu chí kiên nhẫn, các bạn cần phải siêng đi chùa hơn hết mới phải. Vì khung cảnh tịch tịnh của nhà chùa sẽ giúp các bạn mát dịu phần nào nhiệt khí, thấy gương nhẫn nại hy sinh của Phật, các bạn sẽ tăng thêm phần kiên chí. Nghe được giáo lý của Phật sẽ giúp cho phần tư tưởng của các bạn được cao siêu. Như vậy sự đi chùa há vô bổ hay sao?  
