# Tuổi trẻ với hạnh nhẫn nhục {- #tuoi-tre-voi-hanh-nhan-nhuc}

Em là một thiếu niên, quả tim chứa đầy máu nóng, mỗi khi bị ai nhục mạ máu trong người sôi lên, toàn thân nóng rực, rồi em muốn trả thù bằng cách nào cho đã cơn giận dữ. Hoặc khi suy nghĩ sắp làm một việc gì, lòng em nóng nảy bồng bột muốn làm trong chốc lát cho xong.  
  
Sự nóng nảy và nông nỗi ấy đã nhiều lần khiến em phải hối hận và đau khổ. Lắm lúc em cũng muốn bình tĩnh lại, nguội đi một chút, nhưng khi gặp việc rồi cũng chứng nào tật ấy. Vì muốn giúp em một phương tiện để tự chủ lấy mình, tôi xin giới thiệu em hạnh nhẫn nhục do đức Thế Tôn đã dạy.  
  
Nhẫn nhục không có nghĩa là ươn hèn khiếp nhược, khom lưng cúi đầu trước mọi hành động bạo tàn của người mà là kiên gan bền chí nhịn chịu mọi sự mạ nhục, sự khó khổ, sự khen ngợi cũng như sự thắng thế, để hoàn toàn làm chủ lấy mình, để sau rồi xây dựng lại họ.  
  
Muốn nhịn chịu được sự nhục mạ, em nên nghĩ thế này: người mắng ta, vì tại ta làm quấy hay vô cớ tự họ đặt điều?  
  
Nếu ta làm quấy nên họ mắng thì điều ấy rất đáng, còn gì mà phải giận trách. Ðã không giận trách là chớ, mà ta lại phải xin lỗi người là khác. Vì tại ta gây nhân nên họ mới trả quả. Người gây nhân mới là người đáng tội. Như hôm nào đó, em đứng trước sân, bỗng nhiên con Vện rượt con Mèo chạy ngang qua em. Mèo liệu chạy không kịp, đứng lại thủ thế. Vện vừa nhào tới, Mèo vớ cho một cái xể mặt. Trước cảnh đó, em nên trách Mèo hay trách Vện? Cũng thế, ta lầm lỗi bị người mạ nhục, thì nên tự trách, không nên oán giận người. Có thể mang ơn họ là khác, vì họ cho ta một bài học xứng đáng để nhớ mãi mà tránh.  
  
Nếu ta không làm điều gì quấy, vô cớ tự họ bịa chuyện để mạ nhục ta, ta nên nghĩ: Người ấy không biết lẽ phải quấy, họ đã mất hết trí khôn, là một kẻ cuồng không khác, ta chỉ nên thương xót hơn là giận trách. Hơn thua với kẻ cuồng thì ta cũng cuồng nốt. Hơn nữa, nếu em thấy là phải mà bị họ mạ nhục, em cứ lặng im giữ cái phải của em. Nếu em mắng chửi lại họ, thì em cũng quấy như họ. Như có anh chàng mặc bộ đồ trắng muốt đi trên lộ, gặp bọn chăn trâu đang chơi bùn, mình mẩy lem luốc. Chúng ghét cái trắng sạch của anh, nên hốt bùn vãi anh. Lúc đó anh nên chạy, hay nên hốt bùn vãi lại chúng?  
  
Nếu anh muốn giữ cho tròn trắng sạch, cố nhiên anh phải chạy. Cũng vậy, muốn toàn vẹn lẽ phải, em nên nhịn kẻ quấy, đợi qua cơn nóng giận của họ, em sẽ phân giải thì kết quả hơn.  
  
Hoặc giả em là người tốt, kẻ xấu thấy ganh ghét em, họ đến mạ nhục em, khi ấy em nên coi lời mạ nhục như cơn gió thoảng, không cần chống đối. Kẻ mang việc xấu đến; họ sẽ tự chịu xấu lấy. Phật dạy:  

> "Kẻ ác hại người hiền, như ngửa mặt lên trời phun nước bọt, nước bọt không tới trời, trở lại rơi trên mình, như ngược gió tung bụi, bụi chẳng tới người, trở lại làm nhơ mình..."  
> <div class="align-right">-- *(Kinh Tứ Thập Nhị Chương)*</div>  
  
Khi bị mạ nhục, nếu em không dằn được cơn nóng giận, tức nhiên em chửi mắng đánh đập lại họ. Rồi cứ thế mãi, họ vay, em trả; vay trả, trả vay không bao giờ dứt. Như Xoài mắng Ổi, Ổi đánh Xoài. Xoài tìm cách trả thù, Ổi lo phương báo oán, oán thù không biết bao giờ hết. Chi bằng ta áp dụng câu:  

> "Oan gia nên mở không nên kết"  
> <div class="align-right">-- *Khổng Tử*</div>  
  
hoặc câu:  

> "Lấy ân báo oán, oán liền tiêu diệt"  
> <div class="align-right">-- *Đức Phật Thích Ca*</div>  
  
thì nhẹ nhàng rảnh rang biết mấy.  
  
Tuy nhiên, nói thế em sẽ ngờ rằng: Nhịn họ e họ sẽ cho mình là khiếp nhược? - Không! Không phải thế đâu! Em không nhớ Hàn Tín chịu lòn trôn tên du đãng tại chợ Hoài Âm đó sao? Chịu nhục như vậy mà sau này ai dám chê Hàn Tín là khiếp nhược? Nếu có, ấy chỉ là bọn vũ phu thiếu trí mà thôi. Em là người cao thượng có chí lớn, em nhịn những lời nhục mạ của bọn bất lương, không phải vì em sợ họ mà chính vì cái chí lớn của em. Như em có cái chén kiểu quí, có người đem muỗng dừa hay bát sành đến chọi thử với chén quí của em. Khi ấy, em nên chọi hay nên nhịn thua họ?  
  
Thảng hoặc, em cho rằng nhịn họ để bảo vệ tính tốt, lẽ phải và chí lớn của mình, để mặc tình họ gây tội ác, như vậy tỏ ra mình ích kỷ tiêu cực, không có tinh thần xây dựng cho người? Không phải nhịn họ là ích kỷ đâu em! Nhịn là phương pháp lợi người toàn vẹn. Vì khi người ta nóng mới thóa mạ em, khi ấy em cũng nóng, chống đối lại họ. Hai cái nóng cùng gặp nhau thì phải nổ. Như vậy khi nóng giận chống đối người, không có nghĩa là xây dựng họ, mà chính là gây oán thù. Nếu ai nói: *"Tôi chống lại là vì tôi thương, muốn cải thiện giùm họ"*, ấy là lấy lời nhân nghĩa để che đậy cái tính xấu nóng nẩy của mình.  
  
Chẳng những ta nhịn chịu sự nhục mạ, mà còn phải nhịn chịu sự khó khổ. Bởi vì con người sanh trên đời, không phải đến đâu cũng gặp toàn tháp ngà và nhung gấm, mà phải đương đầu với phong ba bão tố. Nguời có sức nhịn chịu được những trở ngại mới mong đạt được kết quả tốt đẹp cao quí. Bằng không nhịn được, dễ sanh nản lòng thối chí. Dù người có sức mạnh cử nổi trái tạ ngàn cân, có tài chọc trời khuấy nước, mà không có chí kiên nhẫn, khi gặp sự thất bại dồn dập đến mình thì nhăn mày, héo mặt, con người ấy không làm nên việc gì đáng kể. Trái lại, người yếu đuối, tài lực tầm thường mà bền gan chịu đựng, mỗi lần vấp ngã chỉ xem đó là một kinh nghiệm, càng thất bại nhiều thì kinh nghiệm càng giàu, chí càng dẻo dai bền vững, con người thế ấy không việc gì làm chẳng được.  

Có vị Tỳ-kheo hỏi Phật:  

\- Cái gì mạnh hơn cả?  

Phật dạy:  

\- Nhẫn nhục mạnh hơn cả. *(Kinh Tứ Thập Nhị Chương)*  
  
Thật vậy, chỉ có người nhịn chịu được mọi khó khăn, vượt qua mọi trở ngại mới mong lập được sự nghiệp vĩ đại trên đời.  
  
Bị nhục mạ, gặp cảnh trở ngại tuy khó nhịn, nhưng người ta dễ biết đề phòng, nên có thể nhịn được. Ðược ngợi khen, gặp việc thắng thế là điều tốt, thỏa thích ý mình, nên ít ai để ý dè dặt, do đó mặc tình tâm phóng túng, gây họa rất to. Như xe vào đường hiểm nguy không lật, mà thường lật ở đường thẳng.  
  
Người bị nhục mạ nhịn không được cơn tức giận, nên gây tai họa, kẻ gặp cảnh trở ngại, nhịn không được lòng buồn nản, nên bỏ hư hỏng công việc, ta được ngợi khen, được thắng thế, nếu không nhịn được lòng tự đắc của mình, nên dễ sinh ngã mạn khiến mọi người đều ghét. Như trò Kiêu lâu nay tuy học dở mà nói năng nhỏ nhẹ khiêm tốn, nên được cả lớp ai cũng thương. Một hôm đến giờ toán, thầy giáo cho bài, may sao anh làm rồi sớm lại trúng, khi các bạn anh làm chưa rồi. Thầy giáo thấy thế khen ngợi anh trước chúng bạn. Có lẽ đây là lần thứ nhất, Kiêu được hơn chúng bạn và thầy khen, mắt anh sáng lên, nhìn chúng bạn thấy họ tầm thường quá. Từ đó về sau, ai trông thấy Kiêu không còn là một trò khiêm tốn dễ thương, mà là đứa bé khinh mạn đáng ghét.  
  
Khi biết nóng giận là tính dữ, nản chí là nết hư, thì ngã mạn cũng là tật xấu. Nhưng khó trị nhất là ngã mạn, vì ta không thể biết được nó khởi tự bao giờ, chỉ có kẻ khác biết thôi. Phật dạy: *"Có thế lực mà không ỷ mình là khó."* Muốn nhịn chịu được sự khen ngợi, ta nên nghĩ thế này:  
  
Tiếng ngợi khen của người đời ít khi đúng sự thật. Hoặc họ muốn làm đẹp lòng ta để nhờ ta giúp một việc gì, nên họ khen? Hoặc họ khen là để gợi tính hiếu thắng, tự cao của ta, đặng đưa ta về chỗ hư hèn? Hoặc vì nể ta, khen cho ta được vừa ý... Tất cả sự khen ấy đều không đúng sự thật, đã không đúng sự thật thì có gì mà ta mừng, tự đắc?  
  
Nếu người khen biết được ta, và trăm phần trăm đúng sự thật, thì ta nên nghĩ: Sự thành công tốt đẹp ấy không phải tài của ta, mà do phước lành đời trước còn lưu lại. Ðã do phước lành mà được việc, khi được ta cần phải gieo giống phước lành nhiều hơn để sau này khỏi mất, mà tính tự cao, ngã mạn là thứ thuốc độc làm ung tất cả mầm phước đức, ta cần phải tránh.  
  
Người gặp những trường hợp trên mà không nhẫn nhục thì sau sanh hối hận. Như Tý bị Sửu mắng, không dằn được cơn nóng, Tý đánh Sửu trọng thương. Anh Sửu trông thấy, nóng lòng vì em, chụp gốc cây đập Tý lỗ đầu. Rốt cuộc cả hai đều trọng bệnh và cùng vào bệnh viện. Như câu cách ngôn Tây phương:  

> Sống vì lưỡi kiếm, chết vì lưỡi kiếm *(Qui vit par l’épée, meurt par l’épée)*
  
Bao nhiêu sự buồn khổ thời gian Tý nằm trong bệnh viện, có phải tại ai có ác ý muốn hại Tý chăng? Hay chính tự Tý chuốc lấy? Sự thực không ai làm khổ mình. Nếu thắng được cơn giận dữ, làm gì Tý phải nằm trong bệnh viện thế này. Cho biết mọi khổ đau đến với mình phần nhiều là tại mình không nhịn được lòng nóng nảy bồng bột của mình mà ra. Như ngài Thích-đề-bà-na hỏi Phật:  
  
\- Vật gì giết an lạc? Vật gì giết vô ưu? Vật gì gốc của độc, nuốt hết tất cả thiện?  
  
Phật đáp:  

\- Sân hận giết an lạc. Sân hận giết vô ưu. Sân là gốc của độc. Sân nuốt tất cả thiện.  
  
Chẳng những thế, người không nhẫn ít khi làm chủ được mình mà thường bị ngoại cảnh chi phối. Như Hận không muốn gây sự với Manh nhưng Manh khiêu khích, không chịu nổi cơn nóng giận, Hận chửi đánh ẩu đả. Thế rồi, cả hai cùng chịu khổ. Hoặc như Tốc muốn học đến cử nhân nhưng thi trung học rớt vài phen, thối chí anh muốn trở về cày ruộng... Những người như thế đều bị hoàn cảnh lung lạc, không có chí vững bền tự chủ.  
  
Người biết nhẫn dù gặp việc lớn cũng biến thành nhỏ, dữ hóa hiền, không mấy khi phải hối hận, tâm thường an lạc. Phật dạy:  

> "Nếu có người trí ưa tu nhẫn nhục, người ấy dáng điệu hòa nhã, hằng tươi tỉnh, ưa vui cười, mọi người trông thấy đều hoan hỉ, nhìn không biết chán..."  
> <div class="align-right">-- *(Kinh Ưu-bà-tắc, phẩm Nhẫn Nhục)*</div>  
  
Lại nữa, người hay nhẫn nhục là đã tạo cho mình một nghị lực phi thường, thắng cả nội tâm và ngoại cảnh. Phật dạy:  

> "Người hay nhẫn nhục mới đáng gọi là bậc hữu lực đại nhân."  
> <div class="align-right">-- *(Kinh Phật Di Giáo)*</div>
  
Thật vậy, bậc đại nhân bao giờ cũng kiên nhẫn, bình tĩnh trước mọi hoàn cảnh. Chỉ có bọn vũ phu mới nóng nảy hấp tấp, làm việc theo nộ khí nhất thời.  
  
Xét qua sự nhẫn nhục, em đã thấy rõ chỗ quí, tiện và lợi hại thế nào rồi. Giờ đây mời em bắt tay vào việc tập luyện hạnh nhẫn nhục. Có thực tập em mới thấy sự lợi ích thiết thực của nó. Ðối với tuổi thiếu niên mà thiếu nhẫn nhục thì không mong thành công, lập nghiệp gì cả. Bởi vì trong lúc thiếu thời, sống về tình cảm hơn lý trí, nên phải tập nhẫn nhục để hạn chế bớt sự sôi nổi bồng bột trong lòng.  
  
Hơn nữa, tuổi thiếu niên em chưa từng nếm mùi cay chua của cuộc đời - nếu có cũng chút ít thôi - nên kinh nghiệm đời em chưa có, vì thế tâm em dễ hăng hái, cũng dễ chán nản. Tập nhẫn nhục sẽ giúp em có đủ thì giờ cho lý trí làm việc, nhẫn nhục sẽ tập cho em có tính bền dẻo khi va chạm cuộc đời. Vì thế đời niên thiếu của em rất cần có nhẫn nhục.  
  
Muốn đạt được hạnh nhẫn nhục, em cần phải quán từ bi. Vì có nước từ bi mới dập tắt được ngọn lửa nóng giận. Từ bi sẽ giúp em hăng hái hoạt động, kiên nhẫn vượt mọi khó khăn để thành công trên công trình lợi tha viên mãn.  
