# Tuổi trẻ với lòng từ bi {- #tuoi-tre-voi-long-tu-bi}

Ðang độ hoa niên lòng tràn đầy vui vẻ, em nhìn cảnh chung quanh đều hiện bày một vẻ tươi sáng đáng yêu. Nét yêu đời biểu lộ trong đôi mắt sáng, trên đôi môi nở nụ cười của em. Em tự thấy cùng mọi người, cùng vạn vật như chung niềm hoan hỉ. Vì thế, lòng yêu thương của em tràn trề vô hạn.  
  
Tuy nhiên, mỗi lần có kẻ đau khổ hiện ra trước mắt em, em tự nghe cõi lòng se lại, mặc dù kẻ ấy không phải bà con thân thuộc của em. Rồi em muốn làm sao cho họ hết khổ, cho họ cùng vui như em. Ấy là "lòng từ bi" đã chớm nở trong lòng em vậy. Em hãy cố gắng vun quén cho nó sanh trưởng sum suê lên.  
  
Nghe nói từ bi, nhưng em chưa hiểu nghĩa thế nào. Ðây, em hãy nghe: Từ bi là lòng thương bao la, lúc nào cũng sẵn sàng san sẻ những nỗi đau khổ của người và đem hạnh phúc an vui cho họ. Lòng thương ấy gieo mầm trên đất khổ đau và sanh trưởng trong ánh sáng trí tuệ. Vì thế, ai mang nặng lòng thương này thì không bao giờ an nhiên khi nhìn kẻ trước mắt mình đang âm thầm nuốt lệ hoặc đang rên siết kêu thương, mà họ nguyện chia sớt, gánh vác cho người vơi đi, nhẹ bớt đôi phần đau khổ.  
  
Lòng thương ấy chẳng phải của riêng ai, mà là chung tất cả. Như trước mắt mọi người, một kẻ cô thế bị bọn côn đồ hoành hành, đánh đập thảm hại, trông thấy cảnh ấy, dù người khô khan thế nào, cũng nghe trong lòng chua xót! Hoặc giả hôm nào đó, em đến hí trường xem một vở bi kịch. Ðến lúc hoạn nạn đau khổ của những vai trên sân khấu, em cũng như người cảm nghe tim đập mạnh, dòng lệ tự nhiên trào!  
  
Nhưng em sẽ nghi ngờ! Tại sao người ta đã sẵn lòng thương yêu nhau khi hoạn nạn, mà trong xã hội hiện tại lại có những kẻ làm nhiều việc táng tận lương tâm, gây cho người một cuộc sống đầy máu và lệ?  
  
Em ạ! Ấy là lòng thương của họ bị hướng dẫn sai đường. Dĩ nhiên lúc thiếu thời, ai cũng có lòng thương rộng rãi, nhưng lớn lên lòng từ bi thu hẹp lại, đặt vào cái khung nhỏ bé, đôi khi bị pha trộn với sự đen tối thành ra mù quáng. Ấy là họ chỉ thấy có vợ, có con và cá nhân họ... , bao nhiêu tình thương đều dồn cả vào cái khung nhỏ hẹp ích kỷ ấy. Mặc ai kêu khóc, mặc ai thở than đều không làm lay chuyển được họ. Thế rồi, để được lòng người yêu, để thỏa mãn cá nhân, họ có ngại gì giày đạp trên hạnh phúc kẻ khác.  
  
Lại nữa, có một số người vô tình hoặc cố ý, họ tự tiêu hoại lòng thương. Như khi gặp một người đói lạnh, anh A nghe lòng thương trào lên, mặc dù trong tay sẵn có phương tiện cứu giúp được, mà anh giả bộ lờ đi không muốn để ý đến. Một lần như thế, hai lần như thế... quen dần, sau này gặp người đau khổ trước mắt, nhưng tim anh đã trở thành sắt đá. Những con người như thế là họ tự tiêu diệt lòng thương rộng lớn, để gom về một cái lạch nhỏ hẹp cá nhân. Một cây cổ thụ rườm rà, nếu mỗi ngày người ta chặt một nhánh, lâu rồi cây ấy chỉ còn một thân đơn trơ trọi.  
  
Trái lại, anh B mỗi lần gặp người hoạn nạn, lòng thương dấy khởi, anh liền tìm mọi phương tiện giúp người. Một lần như thế, nhiều lần cũng thế, đến một hôm gặp người khổ mà không tìm ra phương tiện để giúp, lúc ấy lòng từ bi bị giày vò, lương tâm anh bị cắn rứt, anh tự coi như làm không tròn bổn phận của mình. Rồi anh chạy ngược, chạy xuôi, tìm cho ra phương tiện giúp họ, anh mới yên lòng. Thế là anh B đã biết khai thác lòng thương của mình càng ngày càng sâu rộng.  
  
Em ạ! Lòng thương là một của báu vô giá, nó làm cho người này người khác thông cảm nhau. Nếu em đem một món đồ quí tặng cho người mà em không có lòng thương mến chân thật đối với họ thì món đồ ấy cũng thành vô giá trị. Nếu thiếu lòng thương, thế giới này sẽ đen tối, nhân loại sẽ đi đến chỗ diệt vong.  
  
Ðã là của quí, ai nỡ để lòng thương phải tiêu mòn? Do đó một thiếu niên, em phải bảo vệ tô bồi cho lòng thương càng ngày càng to rộng. Tuy nhiên với tuổi trẻ của em, lòng thương dễ bộc phát, mà cũng dễ lạc lầm. Em cần phải khôn khéo hướng nó đi đúng chiều, phải chỗ. Chỗ thích hợp với lòng thương là cảnh đau khổ, chiều tươi đẹp nhất là ngọn hải đăng trí tuệ.  
  
Ðứng trước cảnh khổ của người, em thấy lòng đau xót, ra tay cứu giúp họ. Bất luận việc nhỏ, việc lớn miễn họ khổ là em thương, em cứu giúp họ. Thế là lòng thương của em chan rải trên mọi nỗi khổ đau của người, để rồi tiêu hoại tất cả mầm đau khổ. Nhờ lòng thương đặt trong cảnh khổ, nên nó bình đẳng, không thiên lệch. Nếu có nghiêng chăng, chỉ nghiêng về đầu cân nào nặng đau khổ. Thấy người đẹp bị khổ em thương, thì gặp người mù đói khát em cũng thương. Chỉ thương ở nỗi khổ của họ, chớ không phải thương vì sắc diện, vì cảm tình. Do đó đức Phật dạy hàng Phật tử muốn khởi tâm từ bi phải quán nỗi đau khổ của chúng sanh.  
  
Thật vậy, có cảm thông nỗi khổ của người mới có lòng thương người chân thật thiết tha. Có thông cảm sự giày vò trong cơn đói của người, em mới sốt sắng cho họ cơm. Có thấu rõ sự buồn tủi, nỗi khổ đau của kẻ tật nguyền, em mới sẵn sàng yên ủi, giúp chén cơm manh áo cho người. Trong kinh Phật có câu: "Ðời là bể khổ." Nói khổ đây, không có nghĩa để người ta chán nản, thở than, mà để nhắc nhở mọi người hãy thương yêu nhau, giúp đỡ nhau và đừng gây khổ thêm cho nhau nữa. Ðời đã khổ lắm rồi, ta hãy san sớt, đùm bọc và nâng đỡ nhau, đừng đổ dồn thêm những tảng đá nặng khi người kia đã kiệt lực. Cùng đi một chuyến tầu, rủi gặp cơn biển động, mọi người đều kinh hoàng khủng khiếp, khi ấy có những người dại sóng ụa mửa dính ta, hoặc đụng chạm vào người ta, nếu không có thuốc cứu giúp họ, không dìu đỡ họ, thì ít ra ta cũng tha thứ những lỗi cỏn con của họ.  
  
Nói thế em sẽ nghi: Lòng thương bắt nguồn từ sự đau khổ, thì những gia đình khá giả, cha mẹ không có đói lạnh, vậy kẻ làm con không thương sao? - Không phải thế đâu em. Mặc dù cha mẹ không phải đói lạnh, nhưng người đã khổ sở nhọc nhằn với con quá nhiều. Từ khi con lọt lòng cho đến khi khôn lớn, kẻ làm cha mẹ đã hồi hộp lo âu cho con biết bao nhiêu lần. Một khi sổ mũi, một chút ấm đầu... của con, cha mẹ đã nóng lòng, sốt ruột, chạy ngược, chạy xuôi lo thầy trị thuốc v.v... Như vậy, kẻ làm con phải biết cảnh khổ ấy, mà thương cha mẹ trước nhất.  
  
Lòng thương phát nguyên từ gia đình lần ra xã hội, như vết dầu loang. Nếu chỉ khu biệt lòng thương trong phạm vi gia đình thì không phải lòng từ bi. Trái lại, thương bao la bên ngoài mà bỏ sót gia đình, ấy cũng không phải từ bi. Lòng từ bi nghĩa là thương khắp hết, nhưng bao giờ cũng từ gần đến xa.  
  
Giống từ bi phải gieo trên đất đau khổ, nhưng cần phải có ánh nắng trí tuệ nó mới nẩy lộc, đâm chồi và đơm hoa kết quả. Có trí tuệ, lòng thương không bị mù quáng lạc lầm. Khi ta gặp hai người cùng đói lạnh, nhưng một người vẻ mặt hiền hòa, cử chỉ đằm thắm dễ thương, một người gương mặt dữ dằn, cử chỉ thô bạo đáng ghét. Nếu thiếu trí tuệ xét đoán, ta chỉ ưng cứu người dễ thương, mà làm ngơ trước người đáng ghét. Thế là, lòng thương đã bị thiên lệch, không còn nghĩa từ bi.  
  
Ðã sẵn lòng thương, nhưng chỉ biết thương để mà thương thì chưa đủ biểu hiện lòng từ bi. Muốn thể hiện lòng từ bi, ta phải ra tay cứu giúp mọi người. Thấy cái khổ của người, ta vẫn coi như cái khổ của ta. Phải thật tâm tận lực cứu giúp họ, mà không mong một sự đền đáp nào cả. Nếu cứu giúp mà mong đền đáp, ấy chỉ là sự cho vay. Cứu giúp không đợi việc lớn mới quan trọng, dù việc bé tí ti mà làm với một tâm lượng rộng lớn, tự nhiên nó trở thành lớn. Ðức Phật xưa kia vẫn hoan hỉ xỏ kim hộ ông A-na-luật-đà. Vì thế, khi ta cứu giúp người, ta không nên chọn lựa việc nhỏ, lớn cũng như kẻ thân, sơ.  
  
Muốn bảo vệ lòng từ bi không cho thối thất, ta phải hạn chế sự phóng túng của mình. Một câu nói đùa có thể tổn thương người, ta không nên nói. Một hành động chơi vui có thể hại mạng loài vật, ta vẫn không chơi. Nhà luân lý học Pháp, ông Vauvenargues nói:  

> Ðối với một người hung tợn nhất dù ai nói thế nào mặc lòng, nếu người ấy hãy còn yêu loài vật thì chưa phải là một người hung tợn.

Người ta nhiều khi vì một trò chơi mà đã tàn sát sanh mạng các loài vật, như bắn chim chẳng hạn. Họ có biết đâu, đó là những hành động làm tiêu ma lòng từ bi của họ?  
  
Cần cho lòng từ bi tăng trưởng, ta phải dẹp bớt tánh vị kỷ, luôn nhớ đến người, đến mọi loài hơn nghĩ đến mình. Nếu có lợi cho bản thân ta, mà đau khổ người hay vật thì nhất định không làm. Cố làm việc hại người, hại vật để thỏa thích thị dục mình, hành động ấy phi từ bi. Sự ăn chay của người tu nhằm mục tiêu này.  
  
Lòng từ bi là ban rải hạnh phúc cho người, cho muôn loài. Cây thiếu nhựa sống thì cây khô héo, con người thiếu từ bi con người khổ não. Có từ bi thì nhân loại mới yêu thương nhau, tương trợ nhau. Làm gì có chiến tranh, làm gì có tang tóc, nếu mọi người sẵn lòng từ bi? Trái lại, nếu con người không có chút từ bi thì thế giới này sẽ thấy dẫy đầy lửa và máu! Cho nên muốn đem hòa bình cho nhân loại, đem hạnh phúc cho chúng sanh, chúng ta phải cực lực cổ võ từ bi. Từ bi đến đâu thì đau thương tan đến đấy.  
  
Từ bi đã quan trọng dường ấy, là một thiếu niên, em đâu thể nào cam chịu để cho lòng từ bi của mình phải tiêu mòn. Em hãy cố gắng khai thác và thực hiện từ bi. Chỉ mong có năng lực thiếu niên mới kham san sớt, gánh vác những đau khổ, nhọc nhằn thế cho người. Nếu đợi đến ngày da dùn gối mỏi, người ta mới nghĩ đến việc từ thiện, việc cứu vớt người thì đã quá muộn màng!  
  
Khoảnh đất tâm hồn của thiếu niên trong trắng, nên rất thích hợp cho giống từ bi sanh trưởng. Vậy em hãy cụ thể hóa lòng từ bi trên hành động, lời nói và ý nghĩ của em. Làm thế nào khi nhìn vào em, người ta thấy là hiện hình của từ bi. Ðược thế, đời sống của thiếu niên mới đáng quí đáng mến.  
