# Tuổi trẻ với vấn đề giải thoát {- #tuoi-tre-voi-van-de-giai-thoat}
  
Ðã lâu, đa số thanh niên quan niệm giải thoát của đạo Phật là siêu hình huyền hoặc đâu đâu, để dành riêng cho những người chán thực tại cầu vào chốn hư vô tịch diệt. Thanh niên là thích thực tế, ưa hoạt động nên không cần để ý đến. Nhưng nếu các bạn chịu khó một chút, nghiền ngẫm lại vấn đề giải thoát, các bạn sẽ than rằng: *"Chúng ta đã lầm! Giải thoát là thực tế, là hoạt động, là hoài vọng mà mỗi chúng ta đang thiết tha ôm ấp, đâu phải là chuyện xa xôi."* Do đó, đem vấn đề này bàn với các bạn, theo tôi thiết nghĩ không phải là việc vô bổ.  
  
Khi đi sâu vào vấn đề, trước phải hiểu nghĩa chính của nó. Giải thoát là gì?  
  
Giải là cởi mở mọi sự trói buộc. Thoát là vượt ra ngoài vòng trói buộc một cách tự do tự tại. Giải thoát là cởi mở tất cả xiềng xích trói buộc, giam hãm con người, để tâm hồn và thể xác hòa điệu cùng vũ trụ bao la một cách tự do tự tại. Ðể được dễ hiểu và gần gũi hơn, chúng ta có thể tạm dùng danh từ tự do thay cho giải thoát.  
  
Có bạn trẻ nào mà không yêu chuộng tự do. Nếu bạn là người sanh trưởng nơi thôn dã, bạn có ưng giam hãm suốt đời mình dưới nếp nhà tranh ấm cúng, trong lũy tre làng thân yêu mãi chăng? Hay bạn ước mơ có ngày sẽ bước chân ra khỏi cổng làng, vượt lên đỉnh núi cao chót vót, nhìn con sông bạc uốn quanh, thửa ruộng vàng mơ dợn sóng. Và một buổi chiều xuân mát mẻ, bạn đứng trên bãi cát trắng phau, lặng nhìn những đợt sóng xanh gầm thét, rượt đuổi nhau trên mặt trùng dương bát ngát, những cánh buồm trắng đang nhấp nhô ở chân trời mờ đục. Chắc là bạn không ưng đóng khung kiến thức, mà muốn phóng tầm mắt nhìn khắp nước non.  
  
Hoặc bạn là người trưởng thành nơi đô thị, bạn có thỏa mãn suốt đời mình cứ khuôn trong gian nhà nóng bức, quanh quẩn chỉ trong vòng thành phố nghẹt người ấy không? Hẳn là không. Bạn đã ôm mộng một ngày nào đó sẽ đạp gió tung mây để góp mặt cùng mọi người trên khắp năm châu thế giới.  
  
Như thế, là các bạn đã ôm hoài vọng giải thoát sự giam hãm, sự đóng khung của kiến thức rồi.  
  
Bạn là một thanh niên, có bao giờ bạn muốn đời mình bị lệ thuộc vào kẻ khác. Nếu vô phúc đã bị, bạn đã có hoài bão một ngày kia bạn sẽ thoát khỏi và rồi vĩnh viễn không bị lệ thuộc vào ai. Ðó là bạn đã có hoài vọng giải thoát sự lệ thuộc của cá nhân vậy.  
  
Hơn thế nữa, chắc nhiều khi bạn cũng mơ tưởng phải làm sao cho thể xác hoàn toàn tự do, tâm hồn khoáng đãng, không còn bị một sự chi phối nào cả. Thế bạn không có mộng giải thoát là gì?  
  
Nói như vậy, không có nghĩa là muốn giải thoát phải bỏ gia đình sống theo lòng dục của mình. Như có một ít thanh niên hiện tại, hấp thụ được một ít cặn bã của nền văn minh Âu Tây, rồi lên tiếng đòi hỏi tự do theo sở thích cá nhân. Họ cho sống trong gia đình bị sự ép buộc câu thúc theo khuôn lý đạo đức khiến họ hết tự do, cần phải đả phá luân lý gia đình, đề cao sự phóng túng cá nhân là được tự do. Quan niệm thế, là lầm to! Ở trong gia đình mà trên ra trên, dưới biết bổn phận dưới, cha hiền con thảo không phải tự do là gì? Nếu sống một mình mặc tình ngông ngông nghênh nghênh, lang thang vô gia cư, vô sự nghiệp thì ai dám bảo đó là tự do?  
  
Thảng hoặc có người bất chấp luật lệ hiện hành của quốc gia, nghênh ngang muốn làm chi thì làm. Họ cho rằng còn theo luật lệ là còn bị câu thúc. Cái hiểu lầm ấy rất hại cho xã hội. Nếu một quốc gia mà mặc tình ai muốn cướp của, giết người... tùy ý thì còn gọi được là quốc gia không? Con người mà tự do đến mức đó, còn có thể gọi là tự do nữa chăng? Thí dụ: Những đại lộ tại Sài Gòn, nếu tất cả loại xe chạy tự do, không cần theo luật lệ đi đường, theo sự điều khiển của cảnh sát viên thì một ngày gây ra biết bao nhiêu tai nạn? Người ta sẽ được tự do, khi nào mọi người đều tuân theo kỷ luật một cách trung thành.  
  
Lại có người bảo: *"Ðạo Phật nói rằng trọng tự do, mà mới vào đạo đã phải giữ giới, như vậy là trói buộc, chớ làm gì có tự do."* Ðó là một hiểu lầm nữa. Chúng ta thấy đoàn xe lửa chạy trên đường rầy, nếu có chiếc nào bất chấp đường rầy thì chiếc ấy ra sao? Hẳn là rơi xuống ruộng, lật nhào và nằm ỳ một chỗ. Như vậy, đoàn xe lửa muốn chạy suốt đến đích của nó đã định, phải theo đường rầy một cách trung thành. Cũng thế, người tu theo đạo Phật cốt mong được giải thoát, giới luật Phật chế ra là con đường rầy để đưa đến mục đích giải thoát. Như Phật dạy đệ tử phải giữ giới không được trộm cướp, nếu Phật tử cãi đi trộm cướp, có ngày bị còng trói và giam hãm trong khám đường. Ấy đủ biết người giữ giới, người không giữ giới, tự do hay mất tự do thế nào rồi.  
  
Các bạn! Những điều trình bày trên cho thấy tai hại của sự hiểu lầm về tự do hay giải thoát. Giờ đây, để thực hiện giải thoát, chúng ta phải theo tuần tự của nó.  
  
Trước giải thoát phần thể xác. Chúng ta không nên hoàn toàn ỷ lại vào ai, dù cha mẹ cũng thế. Người sống chỉ biết ỷ lại là người mất tự chủ. Khi ta mong nhờ ai một điều gì, nếu người ấy bảo ta làm một vài việc không thích ý, nhưng vì để được việc mình, ta buộc lòng cũng phải làm. Ðó mới nhờ một việc thôi, còn mất tự do như vậy, phương chi những kẻ tất cả đều trông cậy vào người khác, thì khác nào khúc gỗ, mặc tình ai lăn đâu thì lăn, chặt, cưa gì cũng được. Ðể sống một cuộc đời giải thoát ta phải tự lực tự cường, sự giúp đỡ của cha mẹ anh em nếu có chỉ là một phần phụ thôi.  
  
Cũng phần thể xác, chúng ta cần phải giải thoát những bệnh ghiền *(nghiện)*. Có ai tự thuở lọt lòng mẹ đã mang bệnh ghiền thuốc điếu, ghiền rượu, ghiền á phiện... đâu, thưa các bạn? Bởi vì do phong tục tập quán của xã hội, hoặc vui chơi tập dần dần thành mang bệnh ghiền. Chúng ta thử xét qua những người mang bệnh ghiền ấy như thế nào.  
  
Người mắc bệnh ghiền thuốc điếu. Tuy thuốc điếu không đắt giá mấy, tùy túi tiền nặng nhẹ mà hút thuốc ngon, thuốc dở và cũng không có hại làm say sưa người; nhưng đã là ghiền thì đều bị ràng buộc cả. Người mắc bệnh ghiền thuốc điếu, nếu khi gặp hoàn cảnh phải nhịn cả buổi, hoặc trọn ngày; lúc ấy ở trên gió ai nhả vài làn khói trắng bay xuống, vì còn tự ái, ý chưa nhất định đi xin mà cặp chân nhắm hướng bước đến. Khi cần đi đâu thì kè kè một đãy, nào giấy, nào hộp quẹt, nào thuốc, nếu lỡ quên một thứ thì nghe bực tức khó chịu.  
  
Ðến ông ghiền rượu. Nếu ông đã quen mỗi sáng một cốc, mỗi chiều một cốc, khi nào thất cữ một cái là ông ụa ọe hàng giờ, ăn không ngon, ngủ không được, rầy vợ, đánh con. Trái lại, sức ông chở nổi một cốc, mà ép đến ba, bốn cốc, thì cũng ụa mửa lai láng, cũng rầy vợ, đánh con. Tới cữ ghiền mà không có rượu, đang làm việc gì cũng bỏ, chạy ngược chạy xuôi đi mượn tiền, hoặc mua chịu mua đựng. Ðã mắc phải cái cảnh ấy thì còn gì là tự do, tự chủ.  
  
Rất nguy hiểm là ông ghiền á phiện. Tiêu nhà hết của, thân thể hao mòn cũng do bị bệnh ghiền này. Cũng may, hiện giờ Chánh phủ đã cấm, không cần phải bàn đến.  
  
Ở đời rất mâu thuẫn, người ta thích tự do, ưa giải thoát mà cũng ưa tập những bệnh ghiền. Khi đã mang một bệnh ghiền là đã tự lấy dây cột trói mình một lớp. Càng mang nhiều bệnh ghiền là tự cột trói mình càng dày càng chặt, những người ấy biết bao giờ trông thấy được chân trời tự do giải thoát. Bởi vậy, thanh niên các bạn đã yêu chuộng tự do, yêu chuộng giải thoát, các bạn nên lánh xa những sự trói buộc này, đừng để mình tự mâu thuẫn lấy mình.  
  
Như thế, mới giải thoát về hình thức. Ðến đây tiến lên một mức nữa, giải thoát tâm hồn.  
  
Về mặt tâm hồn, các bạn nên ý thức rằng: *"Không ai cởi mở được cho ta, chúng ta phải tự cởi mở lấy."* Các bạn đừng nên phó thác cả tâm hồn mình vào một đấng thần linh, một đức Phật hay một thượng đế... nào để mong cứu rỗi. Phật dạy:  

> "Các người phải tự thắp đuốc lên mà đi."

Phần thể xác chúng ta còn không thể ỷ lại được, phương chi về tâm hồn lại tế nhị hơn, mà đem phó thác cả nơi các Ngài sao? Nếu người trông cậy vào một nghị lực của thần linh cứu rỗi để được giải thoát, khác nào kẻ leo núi ôm theo hòn đá to, mong nhờ sức nặng của hòn đá sẽ đưa lên tận đỉnh núi. Nói thế không phải phủ nhận sự gia hộ của các Ngài, nhưng chúng ta phải nhận trách nhiệm chính tự mình cứu rỗi. Nếu có gia hộ chăng, các Ngài chỉ là một phần phụ thôi. Ðức Phật thường dạy:  

> "Ta là ông thầy chỉ đường, đã chỉ đường cho chúng sanh. Nhưng đi hay không đi là tùy chúng sanh, chớ không phải lỗi tại người chỉ đường."
  
Xác thực nhất, tâm hồn muốn được giải thoát, chúng ta phải tiêu diệt phiền não. Anh chiến sĩ muốn trên đường về tự do ca khúc khải hoàn là phải diệt tận quân thù. Nếu quân thù chưa diệt, anh chiến sĩ không mong gì có ngày khải hoàn tươi đẹp. Các bạn trẻ! Các bạn muốn tự do, muốn được giải thoát, trước hết các bạn phải trừ diệt bọn tham, sân, si... và những tính xấu trong người. Như bạn thừa biết khám đường là chỗ không tự do, không bao giờ bạn chịu đến đó. Thế mà, một hôm có thằng nhãi con nào đó chọc tức bạn, bạn không thể dằn được, sẵn trong tay cầm khúc cây to, bạn phang cho nó một cái cho đã giận. Khổ thay! Khúc cây bị nhiệt lực của bạn đẩy quá mạnh va vào đầu, nó té xỉu, máu me lai láng. Liền đó bạn bị điệu về bót và mấy hôm sau dời sang khám đường. Ấy thế bọn tham, sân... ngày nào còn trong người bạn, ngày ấy bạn chưa được tự do. Những việc bạn biết là hại, là xấu, thế mà bị sự thúc đẩy của phiền não rồi bạn phải làm, rốt cuộc bạn phải chịu đau khổ xấu xa. Cho nên tiêu diệt phiền não ở nội tâm, là căn bản của người thích tự do, chuộng giải thoát.  
  
Có lắm người đòi hỏi tự do, mong cầu giải thoát, mà cứ đòi hỏi nơi kẻ khác, mong cầu nơi bề trên, hoặc đôi khi chà đạp tự do của người ta để mình được tự do, những điều ấy thật là việc mò trăng đáy giếng, bắt bóng trên không, làm gì có kết quả. Sao ta không quay lại bản thân ta, tâm hồn ta để đòi hỏi mong cầu, có phải thích hợp, xác thực và chắc chắn không?  
  
Tóm lại, tuổi trẻ là tuổi yêu chuộng tự do, yêu chuộng giải thoát. Ðể đạt được hoài vọng này, các bạn hãy trông cậy vào mình, tranh đấu với mình, khi dứt sạch được những bệnh ghiền, những phiền não... các bạn giải thoát hiện tiền. Ðể được sự hướng dẫn chân chánh, bạn hãy lấy giáo lý của đạo Phật làm tiêu chuẩn cho sự giải thoát. Phật dạy:  

> "Tất cả nước biển chỉ có một vị mặn, tất cả giáo lý của ta chỉ có một vị giải thoát."
  
Sự chú trọng giải thoát như thế là tuyệt đích. Cũng vì thế, giáo lý của Phật rất thích hợp với nhu cầu với khả năng của các bạn. Các bạn hãy mạnh dạn khai triển khả năng mình càng sớm càng hay.  
