# Tuổi trẻ với vấn đề diệt dục {- #tuoi-tre-voi-van-de-diet-duc}
  
Tuổi thanh niên là tuổi hy vọng ước mơ, bao giờ cũng nuôi sẵn trong lòng những mộng đẹp. Nhờ sự hy vọng ước mơ ấy, thanh niên mới phát triển hết khả năng để đạt được sở nguyện. Thế mà, nghe đạo Phật đề cập đến vấn đề diệt dục, thực là một việc cằn cỗi khô khan, không thích hợp chút nào với tuổi đang tràn trề nhựa sống, theo quan niệm của họ. Do đó, đa số thanh niên chỉ đứng xa nhìn đạo Phật, thấy như mình không có liên hệ gì với cái đạo già cỗi ấy.  
  
Sự thật, vấn đề diệt dục có phải bóp chết hy vọng, đốt khô nhựa sống của thanh niên không? - Nhất định là không. Ðó chỉ là một quan niệm sai lầm. Diệt dục không có nghĩa là diệt tất cả ham muốn, mà chỉ là diệt cái đắm mê ngũ dục *(tiền của, sắc đẹp, danh vọng, ăn uống, ngủ nghỉ)* mà thôi. Nếu nói diệt dục là diệt tất cả ham muốn thì tại sao người tu theo đạo Phật còn ham muốn làm điều thiện, ham muốn cứu độ chúng sanh, ham muốn giải thoát, ham muốn giác ngộ...? Bởi vì người đời đắm mê tiền của, sắc đẹp... cho đó là cứu kính của kiếp sống, trở thành mù quáng và nô lệ nó, nên không tìm ra lẽ chánh, Phật nói:  

> "Người nặng lòng ái dục thì không thấy được đạo, ví như nước lóng lấy tay quậy lên, người đến không trông thấy bóng."  
> <div class="align-right">-- *(Kinh Tứ Thập Nhị Chương)*</div>
  
Ðể được sáng suốt và tự do, Phật dạy người đời phải diệt cái đắm mê ngũ dục. Diệt cái đắm mê chớ không phải diệt hết các thứ ấy. Chính sự ăn uống, ngủ nghỉ đức Phật còn phải dùng kia mà. Vì thế, cần nói một danh từ đúng hơn là **Thiểu dục** hay **Tiết dục**.  
  
Tuổi thanh niên là tuổi mong muốn ước mơ, nếu mong muốn xứng với khả năng, hợp với hoàn cảnh là tiến bộ. Trái lại, khả năng một mà mong muốn mười, ước mơ những điều huyễn hoặc viển vông, đó là đi quá đà, chỉ chuốc lấy những thất vọng và đau khổ. Như chàng nông dân kia ước mơ bà công chúa đến phải đau tương tư; hoặc người tàn tật ăn xin nọ ước mơ thành triệu phú mà quên mình đang đói lạnh... Những cái mong muốn ước mơ ấy, nếu không diệt trừ thì con người quên cả thực tại, chỉ sống với mộng tưởng không đâu. Như vậy, vấn đề diệt dục đâu không hệ trọng thiết yếu với tuổi thanh niên?  
  
Phần đông thanh niên đều nuôi mộng to, nhưng nếu là mộng Thạch Sùng hay Sở Khanh thì những thanh niên ấy là những con vi trùng độc của xã hội. Chính họ sẽ là con thiêu thân thui mình trong ngọn lửa sắc, tài... Bởi vì khi đã say men sắc, tài, danh vọng, con người có thể quên tất cả lẽ phải, mất hết lương tri, nhất là tuổi thanh thiếu niên, tuổi bồng bột nông nổi. Xưa nay biết bao người khi đứng ngoài vòng sắc, tài, danh vọng, họ là bạn tốt, chồng hiền, con hiếu... Nhưng đến lúc bị sắc, tài, danh vọng làm lòa mắt, họ sẽ trở thành con bất hiếu, chồng phụ bạc, người phản bạn... Do đó, nếu không hạn chế tâm tham dục, thanh niên rất dễ lao mình xuống hố trụy lạc.  
  
Tuy nhiên, hạn chế tham dục không có nghĩa là ngăn bước tiến của thanh niên, ấy là hướng họ tiến đúng đường, hợp đạo lý. Lòng ham muốn của thanh niên không cùng, không tận, nếu mở khuôn luân lý, đạo đức cho nó mặc tình bay chạy thì thế giới này sẽ trở thành địa ngục, con người không còn nhân phẩm. Nói thế không phải cấm đoán thanh niên không cho ham muốn, ở đây chỉ cần xoay chiều ham muốn ấy trở thành hữu ích và hướng thiện là tốt.  
  
Giáo lý đạo Phật dạy diệt dục, cũng giáo lý đạo Phật dạy tăng trưởng dục. Nếu không nhận định kỹ, người ta thấy mâu thuẫn ở điểm này. Bốn món Như ý túc, trong ba mươi bảy Phẩm trợ đạo của Phật dạy mà Dục như ý túc là đứng đầu, kế mới Tinh tấn. Lại câu thường ngôn của Phật tử nói: *"Tu hành vô dục, đạo quả nan thành."* Thực vậy, có ham muốn người ta mới gắng sức chịu khó làm việc hay tu hành. Thế là, cái ham muốn phải có và đặt nó đứng đầu, khi bước chân vào đạo Phật. Ðạo Phật cấm cái dục ích kỷ, sai lầm và đau khổ, nhưng dạy tăng trưởng cái dục vị tha, sáng suốt và an lạc.  
  
Cái dục hợp lý hữu ích ấy, thanh niên cần phải có và phải có thật to. Như ham muốn làm việc xã hội, giúp ích đồng bào... những cái ham muốn này càng to chừng nào thì danh nghĩa thanh niên càng xứng đáng chừng ấy và xã hội sẽ nhờ đó mà tươi đẹp, vui vẻ biết bao!  
  
Lại ham muốn mở mang kiến thức, khai thông trí tuệ, thanh niên không thể thiếu được, mà phải có một cách thiết tha. Vì trí thức là cái cần có của con người, nên thanh niên phải gắng công khai thác nó. Nhờ có ham muốn mở mang trí thức, các cậu học sinh mới hăng hái học tập, mới nhẫn nhịn được những cơn quở phạt của giáo sư và mới đạt được bản nguyện. Nếu một học sinh học chỉ vì sự bắt buộc của cha mẹ, đến trường để tránh việc gia đình... thì học sinh ấy chỉ là những thằng bù nhìn không hơn không kém. Thế là thành công trên việc nhân nghĩa, đạt được trí tuệ cho mình đều do ham muốn làm động cơ.  
  
Nếu là một thanh niên Phật tử, vấn đề ham muốn lại càng to gấp bội phần hơn. Bởi vì đã xưng mình là con Phật, là đã ám tàng mong muốn làm bậc siêu nhân. Do đó, Phật tử lúc nào cũng một lòng chăm chăm ham muốn ban vui cứu khổ cho mọi loài. Họ say sưa làm việc bố thí, say sưa lo cứu độ chúng sanh. Bởi lòng ham muốn thiết tha ấy, rất nhiều Phật tử coi mạng sống mình nhẹ hơn bông, xem nỗi đau khổ của người nặng hơn đá, họ đã hy sinh làm được những việc khó làm. Nếu đã xưng là Phật tử mà không phát tâm ham muốn ban vui cứu khổ cho người, thì kẻ ấy là cái bia khắc tên không.  
  
Chẳng những chỉ ham muốn ban vui cứu khổ cho mọi loài, mà Phật tử cần phải thiết tha mong muốn được giác ngộ và giải thoát. Bởi sức mong muốn này quá mạnh, nên trên đường đạo, Phật tử tinh tấn không dừng. Họ cố gắng tu tập, bền chí gạn lọc từng cái bợn nhơ phiền não trong nội tâm. Như người gạn lọc từng mảnh quặng trong khối vàng. Nếu thiếu sự mong muốn, ai không thối lui trong khi gặp muôn vàn trở ngại trên đường đạo.  
  
Phật đã đào luyện cho đệ tử cái mộng to vô kể, tức là cái mộng chuyển thế giới khổ đau thành Cực Lạc, xoay con người phàm tục trở nên Thánh hiền. Như vậy cái dục của Phật tử rất to, mà càng to lại càng quí, vì nó hướng đúng đường.  
  
Tóm lại, đạo Phật chủ trương diệt dục, nhưng chỉ diệt cái đắm mê ngũ dục, chớ không phải diệt cái dục cứu thế độ đời, siêu phàm nhập thánh. Tuổi thanh niên là tuổi còn thiếu kinh nghiệm lại nhiều ham muốn, nếu không biết phương pháp tiết chế những cái ham muốn sai lầm, tăng trưởng những cái ham muốn phải hướng thì rất đáng thương hại thay! Ðem vấn đề diệt dục của đạo Phật áp dụng vào đời sống thanh niên không phải là một việc kém cần thiết. Có thế, thanh niên mới sống một đời sống cao siêu quảng đại, và xã hội mới mong có ngày vinh quang rực rỡ.  
