# Tuổi trẻ với vấn đề hổ thẹn {- #tuoi-tre-voi-van-de-ho-then}
  
Nói đến hổ thẹn, đa số thanh niên hiện thời cho đó là tánh của đám thiếu nữ thời "khuê môn bất xuất" còn lưu lại. Những cử chỉ e lệ, rụt rè, nhút nhát là biểu hiện của tính hổ thẹn. Vì thế với cái thời văn minh này phải thủ tiêu tính hổ thẹn ấy đi. Nhưng với Phật giáo, tính hổ thẹn lại được đề cao. Hổ thẹn là chiếc áo trang sức đẹp nhất của người tu. Hổ thẹn là động cơ tiến thủ trên đường hành thiện. Ðể giải quyết nghi vấn này, chúng ta thử xét lại coi tại sao?  
  
Sở dĩ thanh niên hiện thời đòi tiêu diệt tính hổ thẹn, vì hiểu hổ thẹn là mắc cỡ. Một thiếu nữ bất ngờ gặp anh chàng thanh niên thì bước đi khóm róm, lời nói ấp úng, lắm khi lại kiếm chỗ trốn là khác. Bởi sự rụt rè nhút nhát ấy khiến con người mất cả tính tự nhiên.  
  
Tại sao người ta lại hay mắc cỡ? Vì những người ấy không có sức tự chủ, một khi xúc cảnh đột ngột, hoặc bị ai chăm chú đến, đâm ra luống cuống, mất bình thường. Như trước con mắt chăm chú nhìn của người, họ phải cúi mặt chẳng hạn. Con người không tự chủ ấy, dù việc phải việc quấy, họ cũng thấy ngại ngùng sợ sệt trước khi nói hay làm.  
  
Hổ thẹn không phải thế. Vì hổ là hổ với mình, thẹn là thẹn với người. Mỗi khi nghĩ đến việc quấy, ta xấu hổ tự trách rằng: Ta là con người có đủ nhân phẩm thế này, được trí khôn thế kia, mà đi làm điều quấy vậy sao? Lại vì e thẹn chúng bạn phê bình, chỉ trích, nên vừa nghĩ đến việc quấy, ta dừng ngay. Vì thế hổ thẹn là then chốt của cánh cửa tội lỗi. Duy thức học liệt hổ thẹn vào nhóm thiện tâm sở. Hổ thẹn là một động lực ngăn điều quấy, dứt những sự lỗi lầm. Nó rất thiết yếu, quan trọng đối với người dứt ác, tu thiện.  
  
Khi có nghĩ sai, làm quấy, mới có hổ thẹn. Nếu không nghĩ sai làm quấy, bao nhiêu người, hoặc ai đi nữa vẫn không có hổ thẹn. Hổ thẹn là di sản của tính tự chủ, tự trọng. Con người tự chủ nên vừa nghĩ quấy là bị lương tâm dầy vò hình phạt ngay. Bởi biết tự trọng nên rất thẹn thuồng, không muốn để ai chỉ trích, quở trách mình. Vì thế, hổ thẹn không có nghĩa là mắc cỡ. Nếu có, chỉ là một khía cạnh nào thôi.  
  
Con người, nếu không biết hổ thẹn thì còn gì nhục nhã bằng. Vì chính họ không biết xấu hổ với những hành vi bất chánh, lại không sợ người phê bình chỉ trích, kẻ ấy còn việc xấu nào mà không dám làm, điều ác nào mà không dám dự. Cá nhân họ ngày càng rơi sâu xuống hố tội lỗi. Không biết hổ thẹn thì có bao giờ họ thức tỉnh ăn năn. Gia đình nào mắc phải một đứa con như thế, thật là đại vô phúc. Kẻ ấy gần ai, người ta đều nhờm gớm tránh xa, như tránh xa con chuột ghẻ. Những việc thương luân bại lý, những việc tàn ác đê hèn hàng ngày diễn ra trong xã hội, đều do những hạng người này chủ động. Nếu trong một xã hội mà có nhiều người như thế, thật là một tình trạng bi đát vô cùng của xã hội ấy. Ðức Phật dạy rằng:  

> "Nếu con người không biết hổ thẹn thì trên thế gian này không còn biết phân biệt cha mẹ, anh, em, lớn, nhỏ cùng với loài cầm thú không khác."  
> <div class="align-right">-- *(Kinh Tăng Nhất A-hàm, phẩm Tàm Quí)*</div>  
  
Trái lại, người biết hổ thẹn là người cao thượng, liêm khiết. Do biết hổ thẹn đối với bản thân, người ta cố tránh lỗi, dứt quấy để bảo tồn danh dự cá nhân mình. Như cậu A một hôm thấy bạn bỏ quên cây bút chì trên bàn học, cậu định ý lấy giấu để xài. Nhưng cậu bị lòng hổ thẹn quở trách: mình như thế này mà tham à! Nếu bạn nhìn thấy cây bút chì thì phải nói làm sao? Và còn mặt mũi nào thấy chúng bạn... Vì thế, hôm sau vào lớp, A đem cây bút chì trả lại cho bạn.  
  
Lại nữa, tính hổ thẹn chẳng những cải thiện con người xấu trở thành tốt, mà còn làm động cơ thúc đẩy con người tiến bộ trên đường học vấn, cũng như trong các công nghệ. Như một hôm vào giờ trả bài thầy kêu B lên, rủi hôm ấy cô bận việc, học bài không thuộc, lên đọc chữ đặng chữ mất, lộn đầu lộn đuôi... chúng bạn cười ầm lên! Thầy giáo cũng quở trách. Hổ thẹn quá, từ đó về sau dù bận việc gì, cô cũng rán học cho thuộc, không dám bỏ một bài nào. Thực vậy, sự tranh đua học tập, sự cải tiến các ngành kỹ nghệ, đều phát nguyên từ tâm hổ thẹn mà ra.  
  
Những chứng cớ đơn sơ ấy, có thể cho ta thấy sự có mặt của tính hổ thẹn nơi con người nào, người ấy sẽ tốt và tiến cả mọi mặt.  
  
Nơi cá nhân tính hổ thẹn đã đóng vai quan trọng dường ấy, với gia đình và xã hội, hổ thẹn cần thiết thế nào? Bảo vệ được cang thường, luân lý, giữ được gia thanh quốc túy đều nhờ tánh hổ thẹn cả. Như một chàng thanh niên con nhà lễ giáo, gặp lúc vận cùng buộc phải xa quê hương tìm sanh kế. Khi ấy chàng phải sống trong cảnh chung chạ với bọn bất lương, chúng xúi giục chàng góp tay vào việc trộm cướp với chúng. Nhưng chàng nhất mực từ khước, vì chàng nhớ đến danh giá, thể thống của chàng và ông cha chàng. Nhiều khi sự sống quá thiếu hụt, chàng vừa nghĩ nên nhập bọn với chúng để sống, liền đó chàng thấy xấu hổ, tự trách: danh giá ta thế này, tông môn ta thế ấy mà đi ăn trộm à? Thật là nhục nhã hổ thẹn! Nhờ đó, chàng dừng được ý niệm quấy, thà chịu chết chớ không làm điều nhục nhã.  
  
Biết giữ gìn phẩm giá mình, biết tôn trọng thanh danh tổ tiên mình, những con người ấy ở trong xã hội không bao giờ dám làm điều phi pháp. Một người như thế, trăm ngàn người như thế, thì xã hội này có thể nói là cảnh Cực Lạc. Muốn xây dựng xã hội tốt đẹp, trật tự mà phủ nhận tính hổ thẹn, thực là kẻ muốn có quả cam mà gieo hạt ớt. Bởi nhằm mục đích xây dựng xã hội, nên Phật giáo rất chú trọng phát huy tính hổ thẹn.  
  
Tuy thanh niên là tuổi cần phải có nhiều hổ thẹn và gắng nuôi nó càng lớn càng hay. Vì thanh niên là tuổi cầu tiến, nếu thiếu hổ thẹn tức nhiên động cơ tiến thủ đã mất. Tương lai xã hội ở nơi thanh niên, muốn biết xã hội ngày mai tốt xấu thế nào, cứ nhìn thẳng vào thanh niên hiện tại thì rõ. Mà điều kiện cần thiết tạo thành một thanh niên tốt, một phần lớn là do tính hổ thẹn. Vì thế, chúng ta có thể kết luận rằng: Thiếu hổ thẹn, thanh niên dễ trở thành ác độc; thiếu hổ thẹn, xã hội sẽ chìm trong đen tối của dục vọng.  
